### ISSUE TITLE
Connected textures sometimes produce incorrect sprites with other mods

### ISSUE THREAD

**Issue by Lava-Erlow** [PepperCode1/Continuity#446] opened 2024-06-24 21:04 UTC
![2024-06-24_23 51 02](https://github.com/PepperCode1/Continuity/assets/121287473/bbf882e0-8e65-4a70-be0e-b9cd7225c7fb)
![2024-06-24_23 52 48](https://github.com/PepperCode1/Continuity/assets/121287473/4763895b-572d-4964-b896-ee270a9348dd)
After entering the game and entering the world, all glass panels are replaced with compass or clock textures and become normal only if you open "Resource Packs..." and close. I'm not sure if this is a bug of the mod or a problem with vanilla tweaks
1.21 version

**Comment by PepperCode1** [comment] 2024-06-24 21:46
Please provide a full list of mods with mod versions and a full list of all enabled resource packs. For the purposes of testing, try removing as many mods and resource packs as possible until this no longer happens.

**Comment by Lava-Erlow** [comment] 2024-06-24 21:54
![image](https://github.com/PepperCode1/Continuity/assets/121287473/5c4861b1-4e5d-4b15-ac81-31b6c65e714d)
![image](https://github.com/PepperCode1/Continuity/assets/121287473/8d3d05bb-41bd-4630-9c8d-9b1c6ad9f24d)
![image](https://github.com/PepperCode1/Continuity/assets/121287473/c373ed24-237d-4d04-b32d-a48fee5a43c8)
mods
![image](https://github.com/PepperCode1/Continuity/assets/121287473/415c767f-f54b-4273-a4c5-bf25a3133a9a)
resource packs
![image](https://github.com/PepperCode1/Continuity/assets/121287473/8d69eafc-c208-4dda-805b-4dd68345493a)
![image](https://github.com/PepperCode1/Continuity/assets/121287473/2ae9a669-e83d-473f-8683-f51bd6a94243)
![image](https://github.com/PepperCode1/Continuity/assets/121287473/ffb6896c-82c6-4fae-ad02-469c221ec53f)
resources packs from vanilla tweaks

**Comment by PepperCode1** [comment] 2024-06-24 22:41
That is a lot of mods and resource packs. I am not willing to set up that configuration for testing. However, if you would like to try to find the problem, comment if the issue still happens if all mods except Fabric API and Continuity are removed.

**Comment by FlameFire26** [comment] 2024-07-04 14:36
Same here.
I'm testing with my mods, some were different from yours.
What coufused is that it's hard to find one specific mod that cause this. 
Every time I think I have found it, but it happens again when I added other mods back.

**Comment by tajemniktv** [comment] 2024-07-04 16:30
Huh, for me it's sunflower and some other flowers or smth lol
![image](https://github.com/PepperCode1/Continuity/assets/12156943/e83c7539-9f68-4efc-84c3-af7d76c34124)

Logs, along with mod list, vars and specs is at the beginning: https://mclo.gs/8XymbVM

Wasnt happening until I added (some got updated) these mods: (at least I think so...)
![image](https://github.com/PepperCode1/Continuity/assets/12156943/523b01d4-673d-4557-8aac-99789e5a9794)

Narrowed it down to these:
![image](https://github.com/PepperCode1/Continuity/assets/12156943/239bddd9-4c35-49ab-afb1-58f47fd28c47)

Narrowing it further: it is not fabricbettergrass nor fabricskyboxes

further narrow, it must be one of these, im guessing remove reloading screen maybe?:
![image](https://github.com/PepperCode1/Continuity/assets/12156943/80b9829f-7b34-472b-bf91-f9f376473015)

**Comment by tajemniktv** [comment] 2024-07-04 16:50
A-ha! Got it! Adding back RRLS (Remove Reloading Screen, [MODRNITH LINK](https://modrinth.com/mod/rrls)) is causing this to happen! RRLS is present on both my end and OP @Lava-Erlow, could you try disabling it to see whether the issue is gone on your end? 
![image](https://github.com/PepperCode1/Continuity/assets/12156943/36315904-b487-4d54-a4ec-ffe350e459c2)

**Comment by Lava-Erlow** [comment] 2024-07-04 17:02
interesting. As soon as I get home, I'll check it out.

**Comment by PepperCode1** [comment] 2024-07-04 17:08
Testing with only Fabric API, Continuity, Cloth Config, and RRLS, this does not happen, so RRLS is not the problem, or at least not the only problem.

EDIT

I noticed that when switching from BetterVanillaBuilding and BVB Overlays to Patrix, all visible textures are incorrect for a few frames.
![2024-07-04_11 13 43](https://github.com/PepperCode1/Continuity/assets/44146161/028c9afb-1fee-4071-8c6e-62fd29e51577)

However, this is to be expected. This happens because the block atlas was updated, but the chunks were not rebuilt. They are still using the same vertex UVs they were previously baked with, but those UVs are now incorrect. The chunks are rebuilt soon afterwards, which fixes the incorrect textures. Something very similar happens if I remove RRLS and use the following mixin (Yarn) to observe what the world looks like during the resource reload:
```java
@Mixin(SplashOverlay.class)
abstract class SplashOverlayMixin {
	@Overwrite
	private static int withAlpha(int color, int alpha) {
		return color & 16777215;
	}
}
```

**Comment by wangzheyuying** [comment] 2024-07-05 01:36
Same issue
Reloading the material will fix it later, so I didn't pay much attention to it. But it's a hassle to come every time you log in.

**Comment by FlameFire26** [comment] 2024-07-10 08:05
Now have found some relevant mods, which means that when I disable either of the followings, the texture will no longer showing incorrectly:
- **Remove Reloading Screen**
- **No Chat Reports** and **Litematica**/**Minihud**/**Tweakeroo** (at least one of them) with their dependent mod **Malilib** (1.21 version from https://github.com/sakura-ryoko)

<details>
<summary>My full mod list (Bold for the 'maybe' relevent mods I've test)</summary>

advancementinfo-1.20.4-fabric0.91.2-1.4
animatica-0.6.1+1.21
appleskin-fabric-mc1.21-3.0.2
architectury-13.0.3-fabric
armorchroma-1.2.8
balm-fabric-1.21-21.0.11
betterbeds-fabric-1.4.0
BetterF3-9.0.2-Fabric-1.20.4
bettermounthud-1.2.4
BetterPingDisplay-Fabric-1.21-1.1.1
better-selection-1.6.1
betterstats-3.12+fabric-1.21
boosted-brightness-2.2.0+1.20.1
c2me-fabric-mc1.21-0.2.0+alpha.11.106
carpet-extra-1.21-1.4.147
carpet-tis-addition-mc1.21-v1.60.1
chat_heads-0.10.32-fabric-1.20.3
chatanimation-1.0.6
chattools-1.21-v2.2.1
cherishedworlds-fabric-10.0.0+1.21
chunksfadein-1.0.0-1.21
Chunky-1.4.16
cicada-lib-0.8.1+1.21-and-above
clienttweaks-fabric-1.21-21.0.2
cloth-config-15.0.127-fabric
continuity-3.0.0-beta.5+1.21
Controlling-fabric-1.21-18.0.1
CrystalCarpetAddition-mc1.21-v1.5.0
CustomSkinLoader_Fabric-14.20
defaultoptions-fabric-1.21-21.0.5
eating-animation-1.21+1.9.72
enhancedblockentities-0.10.1+1.21
entityculling-fabric-1.6.6-mc1.21
fabric-api-0.100.4+1.21
fabric-carpet-1.21-1.4.147+v240613
fabric-language-kotlin-1.11.0+kotlin.2.0.0
fabricskyboxes-0.7.4+mc1.21
fastquit-3.0.0+1.20.6
ferritecore-7.0.0-fabric
forcecloseloadingscreen-2.2.2
ForgeConfigAPIPort-v21.0.1-1.21-Fabric
fsb-interop-1.4.0+mc1.21-build.54
gugle-carpet-addition-mc1.21-2.8.0+build.48
IAS-Fabric-1.20.6-9.0.1-beta.5
IMBlocker_4.0.9b+1.21
ImmediatelyFast-Fabric-1.2.18+1.21
indium-1.0.34+mc1.21
inventoryhud.fabric.1.21-3.4.22
InventoryProfilesNext-fabric-1.21-2.0.1
### iris-1.7.3+mc1.21
Jade-1.20.5-Fabric-14.1.0
jecharacters-fabric-4.5.13
justenoughbreeding-fabric-1.21-1.2.4
Kiwi-1.20.5-Fabric-14.0.0
language-reload-1.6.1+1.21
lanserverproperties-1.13-fabric
libIPN-fabric-1.21-5.0.2
### litematica-fabric-1.21-0.18.999-sakura.12
litematica-printer-1.21-3.5.0-sakura.2
lithium-fabric-mc1.21-0.12.7
### malilib-fabric-1.21-0.19.999-sakura.6
malitest-fabric-1.21-0.2.0
mica-1.0.1-fabric
midnightlib-fabric-1.5.7
MiniEffects-1.21-Fabric-9.0.1
### minihud-fabric-1.21-0.31.999-sakura.6
mod-loading-screen-1.0.4
modmenu-11.0.1
### NoChatReports-FABRIC-1.21-v2.8.0
NoRefreshScroll-1.21-1.0.9
notenoughanimations-fabric-1.7.4-mc1.21
ObsidianUI-fabric-0.2.7+mc1.21
optigui-2.3.0-beta.2+1.21
owo-lib-0.12.10+1.21
Ping-Wheel-1.9.1-fabric-1.21
### reeses_sodium_options-1.7.2+mc1.21
Resourcify (1.20.5+-fabric)-1.3.6
RoughlyEnoughItems-16.0.729-fabric
### rrls-5.0.1+mc1.21-fabric
RyoamicLights-fabric-0.2.9+mc1.21
screenshot-to-clipboard-1.0.9-fabric
Searchables-fabric-1.21-1.0.1
### show-me-your-skin-1.11.1+1.21
skinlayers3d-fabric-1.6.6-mc1.21
smoothscroll-2.1.0-1.21-hotfix1
sodium-extra-0.5.7+mc1.21
sodium-fabric-0.5.11+mc1.21
symbol-chat-1.21-1.2.3
syncmatica-fabric-1.21-0.3.12-sakura.4
tcdcommons-3.12+fabric-1.21
TES-fabric-1.21-1.5.5
trashslot-fabric-1.21-21.0.2
tweakermore-mc1.21-v3.19.0
### tweakeroo-fabric-1.21-0.20.999-sakura.11
videotape-1.3.0
visuality-0.7.6+1.21
WindowedFullscreen-1.18-fabric-1.0.1
world_preview-fabric-1.21-1.3.0
XaeroPlus-2.15+fabric-1.21-WM1.38.8-MM24.2.1
Xaeros_Minimap_24.2.1_Fabric_1.21
XaerosWorldMap_1.38.8_Fabric_1.21
YetAnotherConfigLib-3.5.0+1.21-fabric
zume-1.0.0

</details>

**Comment by PepperCode1** [comment] 2024-08-01 21:16
I still do not know what causes this and I have not been able to reproduce it. If anyone wants to help debug this, I need the **smallest possible set of mods** with which this bug happens at least some of the time. All current reports that have provided mod lists here or in duplicate issues have had too many mods installed for the information to be useful for debugging.

**Comment by PepperCode1** [comment] 2024-08-02 00:13
I assembled a mod list containing only the common mods from the four mod lists that were provided across this issue and #482. I still could not reproduce this issue. No amount of restarting the game, rejoining the (singleplayer) world, reloading resources, reloading chunks, enabling/disabling Continuity's Default Connected Textures resource pack, or changing resource pack order caused the issue to appear. Other than the Default Minecraft and Fabric built-in resource packs, I was only using Continuity's Default Connected Textures resource pack.

Mods:
- cloth-config 15.0.127
- continuity 3.0.0-beta.5+1.21
- enhancedblockentities 0.10.1+1.21
- entityculling 1.6.6
- fabric-api 0.100.8+1.21
- fabric-language-kotlin 1.11.0+kotlin.2.0.0
- fabricloader 0.15.11
- fabricskyboxes 0.7.4+mc1.21
- ferritecore 7.0.0
- immediatelyfast 1.2.18+1.21
- indium 1.0.34+mc1.21
- iris 1.7.3+mc1.21
- java 21
- languagereload 1.6.1+1.21
- lithium 0.12.7
- minecraft 1.21
- modmenu 11.0.1
- nochatreports 1.21-v2.8.0
- notenoughanimations 1.7.4
- reeses-sodium-options 1.7.3+mc1.21
- rrls 5.0.1+mc1.21-fabric
- sodium 0.5.11+mc1.21
- sodium-extra 0.5.7+mc1.21
- yet_another_config_lib_v3 3.5.0+1.21-fabric

**Comment by tajemniktv** [comment] 2024-08-02 10:37
I... I can't reproduce it either right now? Except that now adding RRLS somehow removes "Minecraft" logo on the main title screen, but that's their issue I guess?

Full logs, along with that big ass long mod list: https://mclo.gs/4QSDd81
I did make some changes to it, but it wasn't anything crazy I think...? 

EDIT: I did start using a different resourcepack I believe, swapped from Vanillaccurate + PiXLL to Heavily ustomized Realiscraft (from ScorpioGraph), along with some other ones (like optimized models, Dynamic Surroundings [resourcepack] or stuff like that)

![image](https://github.com/user-attachments/assets/c58d862d-e600-4445-9eef-e6fc3dc5e34b)

**Comment by PepperCode1** [comment] 2024-08-02 12:11
Does it happen if you downgrade RRLS to version 5.0.1?

**Comment by embeddedt** [comment] 2024-08-03 14:41
Has anyone been able to reproduce this without RRLS? I had a report of similar issues on the ModernFix side and apparently disabling RRLS was enough to fix it.

I suspect RRLS is the culprit here as it seems very risky to be suppressing the reloading overlay while resources are being changed under the game's feet.

I also suspect the resource reload has to take long enough to complete for the bug to actually happen, which would explain why testing with a few mods never reproduces the issue.

(Credits to some dedicated people in my Discord server for shuffling mod sets around to narrow this down.)

**Comment by dima-dencep** [comment] 2024-08-03 14:45
Actually no, the game level is rendered behind the overlay, but the only things that are disabled on (re)loading are the mouse/keyboard handler, and the screen render

**Comment by dima-dencep** [comment] 2024-08-03 14:46
What might have caused this issue should have been fixed in one of the latest versions of rrls (Otherwise it is not rrls, however I will not deny that it can cause this issue)

**Comment by Polarite** [comment] 2024-08-03 15:11
> What might have caused this issue should have been fixed in one of the latest versions of rrls (Otherwise it is not rrls, however I will not deny that it can cause this issue)

hello there! I can say that RRLS is the reason of this bug, because its more of a race against time, if modpack is big enough and you load in a world before loading isnt fully finished the game will have broken textures, F3+T fixes the issue which makes me think that maybe RRLS doesnt refresh textures after loading in the game first time but does so when using F3 T debug.

EDIT: me and few people managed to narrow a "modpack" with this issue down to only 6 mods installed. Feels like only having one mod with textures inside is enough to make this bug occur.
ModList:
cloth-config-15.0.128-fabric.jar
continuity-3.0.0-beta.5+1.21.jar
fabric-api-0.100.8+1.21.jar
fabric-language-kotlin-1.11.0+kotlin.2.0.0.jar
modernfix-fabric-5.19.0+mc1.21.jar
NoChatReports-FABRIC-1.21-v2.8.0.jar
rrls-5.0.6+mc1.21-fabric.jar

we were suspecting modernfix was the culprit but in this issue people managed to replicate issue without it, those mods have nochatreports in them which has some textures to add to atlas, making loading time ever so slightly longer...

**Comment by dima-dencep** [comment] 2024-08-03 18:40
And so, what ever I did, I even tested rrls on craftoria (don't know modpack which will be bigger) but I didn't have this issue...

**Comment by Polarite** [comment] 2024-08-04 21:08
Since there was no progress in this topic since yesterday, here is a pack I used for testing, its a race condition so I rather if you import and test few times every change to help detecting the issue.

[test pack.zip](https://github.com/user-attachments/files/16488925/test.pack.zip)

github wont let me import in mrpacks so you have to change the extension to mrpack.

**Comment by VaporeonScripts** [comment] 2024-11-19 14:30
> ![2024-06-24_23 51 02](https://private-user-images.githubusercontent.com/121287473/342493119-bbf882e0-8e65-4a70-be0e-b9cd7225c7fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMjY4ODMsIm5iZiI6MTczMjAyNjU4MywicGF0aCI6Ii8xMjEyODc0NzMvMzQyNDkzMTE5LWJiZjg4MmUwLThlNjUtNGE3MC1iZTBlLWI5Y2Q3MjI1YzdmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQxNDI5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDQ0NjFhMGY2YWU0Nzg2ZDk1NTU4MmJhNmQ1NzM0YTgxZWQwYzY2ODg1NDUyMjI1MzllOTk1ZjM3ZWY2MzYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.P2O2MT2i5lKCcbGEdby0FnL7x3sQFTWETRHlsTru8no) ![2024-06-24_23 52 48](https://private-user-images.githubusercontent.com/121287473/342493127-4763895b-572d-4964-b896-ee270a9348dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMjY4ODMsIm5iZiI6MTczMjAyNjU4MywicGF0aCI6Ii8xMjEyODc0NzMvMzQyNDkzMTI3LTQ3NjM4OTViLTU3MmQtNDk2NC1iODk2LWVlMjcwYTkzNDhkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQxNDI5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmVjMWUyNTdiZTViYjc3Zjg5MmNhODhjZDQ3YzI5OWNhNzg4YWM5Y2UxNTE2ZjU4NmM4Zjk2NTM3ODE2OTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LOqbdTCfTCamutGCs9Um0asNFwSFGA7eaIveZ-FKnOA) After entering the game and entering the world, all glass panels are replaced with compass or clock textures and become normal only if you open "Resource Packs..." and close. I'm not sure if this is a bug of the mod or a problem with vanilla tweaks 1.21 version

same happens with me, all glass show me random mob textures, like bees or piglins :skull:

**Comment by VaporeonScripts** [comment] 2024-11-19 15:07
![image](https://github.com/user-attachments/assets/6d6bbf92-34f5-4053-9089-b7f527282725)
i dont have rrls

**Comment by dima-dencep** [comment] 2024-11-19 16:02
skill issue then

**Comment by VaporeonScripts** [comment] 2024-11-19 16:11
lemme correct u: mod issue then *

**Comment by PepperCode1** [comment] 2024-11-26 19:01
It seems this no longer happens as a result of an RRLS update. #544 is a different issue.

**Closed as completed by PepperCode1** 2024-11-26 19:01 UTC
Labels: needs investigation
