### ISSUE TITLE
Falling blocks

### ISSUE THREAD

**Issue by Jopiefrikandel** [PepperCode1/Continuity#184] opened 2022-10-31 17:28 UTC
As soon as there are falling blocks, my game crashes. I've had that happen to me 3 times in the last five minutes only.

**Comment by TheNukeLore** [comment] 2022-10-31 17:32
Make sure you have a mod called indium installed.

**Comment by TheNukeLore** [comment] 2022-10-31 17:32
That’s assuming you use sodium that is.

**Comment by PepperCode1** [comment] 2022-10-31 19:32
Duplicate of #107; install Indium.

**Closed as completed by PepperCode1** 2022-10-31 19:32 UTC
