### ISSUE TITLE
continuity does not work correctly with the sodium mod

### ISSUE THREAD

**Issue by SinedKadis** [PepperCode1/Continuity#264] opened 2023-06-17 16:31 UTC
[latest.log](https://github.com/PepperCode1/Continuity/files/11779541/latest.log)
When I try to install the UltimaCraft resource pack, it throws an error and removes all installed resource packs
[UltimaCraft_(v.1.2)_(1.18).zip](https://github.com/PepperCode1/Continuity/files/11779552/UltimaCraft_.v.1.2._.1.18.zip)

**Comment by YukiAyase** [comment] 2023-06-17 19:04
Install Indium
https://modrinth.com/mod/indium/version/1.0.18+mc1.20

**Comment by PepperCode1** [comment] 2023-07-08 15:22
Duplicate of #107.

**Closed as completed by PepperCode1** 2023-07-08 15:22 UTC
