### ISSUE TITLE
Game crashes after loading the world

### ISSUE THREAD

**Issue by msameer** [PepperCode1/Continuity#496] opened 2024-08-09 21:49 UTC
You start hearing in-game sounds then it crashes before you see the world.
Crash log:
[crash-2024-08-10_00.44.40-client.txt](https://github.com/user-attachments/files/16567182/crash-2024-08-10_00.44.40-client.txt)

**Comment by vico93** [comment] 2024-08-09 23:02
Duplicate of https://github.com/comp500/Indium/issues/324

**Comment by Nik4lo** [comment] 2024-08-11 17:14
Make sure you have right fabric api version my is: [1.21] Fabric API 0.100.8+1.21
I had crashes when using continuity with shaders but CurseForge installed wrong fabric api version

![rhethejh](https://github.com/user-attachments/assets/cc1417cc-4d13-4ce4-9540-6d9ebf394062)

**Comment by PepperCode1** [comment] 2024-08-15 18:02
Update Indium.

**Closed as not planned by PepperCode1** 2024-08-15 18:02 UTC
