### ISSUE TITLE
crashing when gravity blocks fall

### ISSUE THREAD

**Issue by Stiofan63** [PepperCode1/Continuity#112] opened 2022-06-09 05:39 UTC
Appears to be the cause of crashes in 1.19 when gravity blocks fall.  Crash does not occur when continuity is removed (renamed to .bak).  Has been reported by multiple people on Fabric.  Some commentators noted it was continuity and another person confirmed it stopped crashing when they took out continuity.

**Comment by PepperCode1** [comment] 2022-06-09 05:43
Duplicate of #107.

**Closed as completed by PepperCode1** 2022-06-09 05:43 UTC
