### ISSUE TITLE
Crashes with Sodium/BetterNether

### ISSUE THREAD

**Issue by quiqueck** [PepperCode1/Continuity#114] opened 2022-06-09 11:09 UTC
We are currently having an issue with a crash related to Continuity, Sodium and BetterNether (quiqueck/BetterNether#3).
I've done some simple testing (mainly disabling our custom emissive material and model loader code), but the error seems to persist. However, to move forward I would need a little help.

It seems that this static initializer is called before the fabric renderer is ready:
https://github.com/PepperCode1/Continuity/blob/9686d62bde4311ad9b0fd974dbeaf57135e311cc/src/main/java/me/pepperbell/continuity/client/util/RenderUtil.java#L38

If BetterNether is causing this error, you may be able to track down the call that triggers the initialization in the debugger. But it may not be related to BetterNether at all, as the crash also goes away when removing Sodium.

The minimum ste of Mods required to reproduce the issue is:
- bclib 2.0.1
- betternether 7.0.1
- continuity 2.0.0+1.19
- sodium 0.4.2+build.16

**Comment by PepperCode1** [comment] 2022-06-09 13:58
Duplicate of #107.

**Closed as completed by PepperCode1** 2022-06-09 13:58 UTC
