### ISSUE TITLE
Problem with textures

### ISSUE THREAD

**Issue by Gatora1145** [PepperCode1/Continuity#321] opened 2023-10-17 06:52 UTC
When downloading the texture pack for glowing ore, the textures are overlap each other.
I tried to change mods, and the mod itself, changed textures, to no avail...
Build version 1.20.1 Fabric, used Sodium and Indium.

![image](https://github.com/PepperCode1/Continuity/assets/111356441/ec17a0db-6e6c-4b24-8e9f-065ae3c45a40)
![image](https://github.com/PepperCode1/Continuity/assets/111356441/1f6bf773-ef49-4579-9966-a6693c98770e)

**Comment by Gatora1145** [comment] 2023-10-17 06:53
I installed old versions of the mod and other mods, but after installing sodium 5.2, minecraft crashed with any texture pack for glowing ores.

**Comment by hexadecimal233** [comment] 2023-10-17 09:33
already reported
duplicate of #292

**Comment by Gatora1145** [comment] 2023-10-17 11:35
Fnx

**Closed as completed** 2023-10-17 11:36 UTC
