### ISSUE TITLE
Wrong texture of glass when open the game ( Fabric )

### ISSUE THREAD

**Issue by kuni-hoangnguyen** [PepperCode1/Continuity#476] opened 2024-07-21 23:58 UTC
![javaw_NrCtJAdUib](https://github.com/user-attachments/assets/5dbf0b50-0716-404e-9479-b45fc26fab41)
Sometimes when I open the game, this bug will appear; only the glasses will be affected.

**Comment by PepperCode1** [comment] 2024-08-01 20:52
Duplicate of #446.

**Closed as not planned by PepperCode1** 2024-08-01 20:52 UTC
