### ISSUE TITLE
no glass connection

### ISSUE THREAD

**Issue by letakkak32** [PepperCode1/Continuity#82] opened 2022-04-02 07:09 UTC
Same as title. Glass textures are not connected
![2022-04-02_16 03 12](https://user-images.githubusercontent.com/91174583/161371444-2fbea822-9160-4b98-af4d-73b0491051f2.png)
![image](https://user-images.githubusercontent.com/91174583/161371467-cd00741e-81eb-49c3-860f-b95d75d5828d.png)
![image](https://user-images.githubusercontent.com/91174583/161371478-7c0786f7-80d0-4193-93de-2eef1777c596.png)

**Comment by twxes** [comment] 2022-04-02 12:01
me 2

**Comment by KaspianDev** [comment] 2022-04-02 12:33
can confirm 1.1.0-1.18.2

**Comment by PepperCode1** [comment] 2022-04-02 16:01
I'm not even going to ask for a log because this is certainly the same issue that has already been reported three times.
Duplicate of #68.

**Closed as completed by PepperCode1** 2022-04-02 16:01 UTC
