### ISSUE TITLE
Game + Launcher crashing when gravel falls

### ISSUE THREAD

**Issue by DEMEMZEA** [PepperCode1/Continuity#180] opened 2022-10-18 23:55 UTC
[2022-10-18-6.log.gz](https://github.com/PepperCode1/Continuity/files/9815716/2022-10-18-6.log.gz)
[crash-2022-10-18_20.23.34-client.txt](https://github.com/PepperCode1/Continuity/files/9815717/crash-2022-10-18_20.23.34-client.txt)

**Comment by PepperCode1** [comment] 2022-10-18 23:56
Duplicate of #107; install Indium.

**Closed as completed by PepperCode1** 2022-10-18 23:56 UTC

**Comment by DEMEMZEA** [comment] 2022-10-19 00:08
Sorry, i thought I had already done that.
