### ISSUE TITLE
(1.19.4 Fabric) In-game text being completely broken.

### ISSUE THREAD

**Issue by Overkill77** [PepperCode1/Continuity#306] opened 2023-08-20 08:51 UTC
Here are the logs:
https://mclo.gs/mkpWj8T

Problem:
As seen in the screenshots bellow, all in-game text is squares, have tried to diagnose the problem and find the conflicting mod to no avail, no the absence of indium, is not the issue here, since with only continuity enabled, it works perfectly fine.

Screenshots: 
![image](https://github.com/PepperCode1/Continuity/assets/43915146/e87c0d34-c47e-4ca8-8d39-2f12132ccfb7)
![image](https://github.com/PepperCode1/Continuity/assets/43915146/79592e7a-6641-4a51-b420-228de2a4b963)
The screenshots display the problem occurring with both fancymenu disabled and enabled. Showing both as at first I thought it was an issue with said mod.

**Comment by Overkill77** [comment] 2023-08-20 09:05
I have actually found the issue. It seems that continuity and [Simple hats](https://modrinth.com/mod/simple-hats) are incompatible, and that it has been an [Issue](https://github.com/fonnymunkey/SimpleHats/issues/10) since november 13th 2022.

While my problem is different than the one stated in that issue, removing simple hats does seem to fix this text error.

**Comment by PepperCode1** [comment] 2023-08-20 15:11
You did not install Indium. Duplicate of #107.

**Closed as completed by PepperCode1** 2023-08-20 15:11 UTC
