### ISSUE TITLE
NPE crash on 1.19

### ISSUE THREAD

**Issue by lbenedetto** [PepperCode1/Continuity#138] opened 2022-07-05 18:44 UTC
[crash-2022-07-05_11.42.05-client.txt](https://github.com/PepperCode1/Continuity/files/9048735/crash-2022-07-05_11.42.05-client.txt)

**Comment by AlsoSylv** [comment] 2022-07-05 19:45
Duplicate of #107, install indium

**Closed as not planned** 2022-07-05 19:50 UTC
