### ISSUE TITLE
1.19 Textures not connecting.

### ISSUE THREAD

**Issue by PuffleNamedHuffle** [PepperCode1/Continuity#152] opened 2022-08-07 21:37 UTC
![huge_2022-08-07_17 35 19](https://user-images.githubusercontent.com/110790214/183311814-e028099e-24e6-4cdc-92dd-091be2bbeafc.png)

I have both Sodium and Indium installed, along with some other mods. I don't believe that I have any mods that don't work with Continuity, and I have both Resource packs open. What should I do?

**Comment by PepperCode1** [comment] 2022-08-07 21:37
Send a log or list of mods.

**Comment by PuffleNamedHuffle** [comment] 2022-08-07 21:45
advancementinfo-1.19
animatica
antighost
architectury
bettermounthud
borderless-mining
capes
capybara
cem
charm
chime
citresewn
cloth-config
clumps
colormatic
contnuity
cosmeticarmorreworked
culllessleaves
debugify
distanthorizons
dynamic-fps
enhancedblockentities
entity-texture-features
entityculling
fabric-api
fabric-chunkpregen
fabric-language-kotlin
fabrishot
farsight
ferritecore
fpsreducer
frameless
illuminations
induim
inmis
iris-mc
item-model-fix
lambdabettergrass
lambdynamiclights
language-reload
lazydfu
lithium-fabric
logical-zoom
main-menu credits
memoryleakfix
midnightcontrols
mixinconflicthelper
modmenu
morechathistory
moreculling
nochatreports
nofade
notenoughcrashes
optigui
puzlle
reeses_sodium_options
rei
smoothboot
sodiumextra
sodium
starlight
tooltipfix
trinkets
yosbr
zoomify

Is this good?

**Comment by PepperCode1** [comment] 2022-08-07 21:45
Mod versions are also needed.

**Comment by PuffleNamedHuffle** [comment] 2022-08-07 21:46
is there a way to get a complete list without writing it all? Im not that good at using files

**Comment by PepperCode1** [comment] 2022-08-07 21:48
Actually, nevermind. The two mods that would have caused this issue are not present in your list. A log is indeed necessary. It can be found in `.minecraft/logs/latest.log`. Please upload it to a paste site instead of pasting the text here.

**Comment by PuffleNamedHuffle** [comment] 2022-08-07 21:48
ok i will! thanks so much btw

**Comment by PuffleNamedHuffle** [comment] 2022-08-07 21:57
Does it have to be the whole log? It is really hard to copy and paste it for me into pastebin.

**Comment by PepperCode1** [comment] 2022-08-07 21:58
Yes, the whole log. If it is so large you cannot paste it anywhere then upload the file directly to Github.

**Comment by PuffleNamedHuffle** [comment] 2022-08-07 21:59
Ok Ill try once more to copy, if it doesn't I will just upload

**Comment by PuffleNamedHuffle** [comment] 2022-08-07 22:06
It is too big for github, where should I share it?

**Comment by PepperCode1** [comment] 2022-08-07 22:07
In this case, share as much as you can starting at the very bottom of the file and going up.

**Comment by PuffleNamedHuffle** [comment] 2022-08-07 22:08
I think i got it through mediafire

**Comment by PuffleNamedHuffle** [comment] 2022-08-07 22:09
https://www.mediafire.com/file/v1a18ucsgv0swh1/latest.log/file 

does that work

**Comment by FwuffyPetsOwO** [comment] 2022-08-07 22:27
This log is extremely convoluted. Could you find the minimum combination of mods for this issue to occur?

**Comment by PuffleNamedHuffle** [comment] 2022-08-07 22:28
What do you mean by that?

**Comment by FwuffyPetsOwO** [comment] 2022-08-07 22:30
Could you find a combination of mods that causes the issue, such that:
- If you add any other mods, the issue persists
- If you remove any one mod, the issue is no longer present

This will give a clearer log which will help us find the source of the issue more efficiently

**Comment by PuffleNamedHuffle** [comment] 2022-08-07 22:33
I already tried that and it didn't really help. Thats why I came here.

**Comment by FwuffyPetsOwO** [comment] 2022-08-07 22:35
We can't properly help either because the log you have is swamped with errors provided by other mods that are unrelated to the issue. I would suggest first trying with just Sodium, Indium, and Continuity and see if that works, then add in your mods to see which one causes the issue to occur.

**Comment by ventus212** [comment] 2022-08-07 22:51
i have experienced the same well in 1.19.1 is the anyway to fix it? thank you :)
this is my mods list
1. Continuity-Mod-Fabric-1.19.1
2. fabric-api-0.58.5+1.19.1
3. iris-mc1.19.1-1.2.6
4. modmenu-4.0.5
5. replaymod-1.19.1-2.6.7
6. sodium-fabric-mc1.19-0.4.2 (replaymod compatible)

**Comment by FwuffyPetsOwO** [comment] 2022-08-07 22:52
@ventus212 you need Indium for Continuity to work with Sodium

**Comment by PuffleNamedHuffle** [comment] 2022-08-07 22:53
Ok I will try that thanks.

**Comment by ventus212** [comment] 2022-08-07 22:57
![image](https://user-images.githubusercontent.com/110792045/183314270-c2b825bc-a4fd-4cea-b574-b66be061062b.png)

**Comment by ventus212** [comment] 2022-08-07 22:59
i tried it with indium but the game crashed

**Comment by PuffleNamedHuffle** [comment] 2022-08-07 23:35
So I tried it with the basic mods; sodium, iris, indium, continuity, fabric api, and sodium extra and it still isn't working.

**Comment by PuffleNamedHuffle** [comment] 2022-08-07 23:37
What should i do?

**Comment by FwuffyPetsOwO** [comment] 2022-08-08 00:23
Apologies for the delayed reply, I had to go do stuff. In any case, could you send the log from the time just used just the basic mods? This is rather interesting ...

**Comment by PuffleNamedHuffle** [comment] 2022-08-08 00:30
yes give me a second.

**Comment by PuffleNamedHuffle** [comment] 2022-08-08 00:37
[latest.log](https://github.com/PepperCode1/Continuity/files/9277880/latest.log)

**Comment by FwuffyPetsOwO** [comment] 2022-08-08 00:45
Could you try without Sodium Extras?

**Comment by PuffleNamedHuffle** [comment] 2022-08-08 00:47
Ok

**Comment by PuffleNamedHuffle** [comment] 2022-08-08 00:47
But i had this problem even before i installed sodium extra

**Comment by FwuffyPetsOwO** [comment] 2022-08-08 00:49
The errors in the log are just weird

**Comment by PuffleNamedHuffle** [comment] 2022-08-08 00:49
if it doesn't work at this point I might as well just add a custom mc resource pack that textures them differently

**Comment by PuffleNamedHuffle** [comment] 2022-08-08 00:50
ok minecraft is booting up

**Comment by PuffleNamedHuffle** [comment] 2022-08-08 00:53
[latest.log](https://github.com/PepperCode1/Continuity/files/9277917/latest.log)

**Comment by asundrus** [comment] 2022-08-10 10:11
Sorry to jump into your topic, but I just wanted to share my modlist which works without errors, I don't know if this can help in any way:

**carpet-extra-1.19.1-1.4.83.jar
continuity-2.0.0+1.19.jar
effectmc-fabric-1.19-2.1.0.jar
fabric-api-0.58.5+1.19.1.jar
fabric-carpet-1.19.1-1.4.83+v220727.jar
fabric-language-kotlin-1.8.2+kotlin.1.7.10.jar
healthcare-1.2.0.jar
indium-1.0.7+mc1.19.jar
InventoryProfilesNext-fabric-1.19-1.6.1.jar
iris-mc1.19.1-1.2.6.jar
litematica-fabric-1.19.2-0.12.3.jar
malilib-fabric-1.19.2-0.13.0.jar
minihud-fabric-1.19.2-0.23.3.jar
modmenu-4.0.6.jar
sodium-fabric-mc1.19-0.4.2+build.16.jar
tweakeroo-fabric-1.19.2-0.14.3.jar
worldedit-mod-7.2.12.jar
WorldEditCUI-1.19+01.jar
XaerosWorldMap_1.26.2_Fabric_1.19.1.jar
Xaeros_Minimap_22.13.0_Fabric_1.19.1.jar**

**Comment by Steccah** [comment] 2022-08-12 10:26
I have the same issue, i have the basic mods and it doesn't work
[Here's my log](https://mclo.gs/XyvpEBS)

**Comment by Steccah** [comment] 2022-08-12 10:51
Damn i didn't know i had to activate the resource packs, you should check that

**Comment by DeWolfRobin** [comment] 2022-08-14 08:16
I had the same issues, the fix I had was indeed to use the resource packs. I couldn't find any information on it anywhere, but you just go to resource packs and enable them there, the mod auto-includes them but doesn't activate them.

**Comment by Arcensoth** [comment] 2022-08-21 21:28
@PepperCode1 I did a bunch of debugging and thought it might be worth posting my findings here in case it helps diagnose incompatibilities like this. So, for what it's worth:

I had the same issue (textures not connecting) and narrowed it down to the mod Inspecio which uses/bundles Quilt APIs. From what I've read, mods that use/bundle Quilt APIs can apparently cause issues with Fabric APIs. (And in fact updating to a newer version of Fabric API with Inspecio included in the mods folder caused my game to crash during boot.) Specifically, Inspecio causes the built-in "Fabric Mods" resource pack to disappear from my resource pack menu. Either directly or by the same root cause, I expect this is also what causes Continuity to malfunction.

@PuffleNamedHuffle I'd recommend combing through your mods to see if any use/bundle Quilt APIs, and, if they do, try removing them one by one to see if that solves the problem.

**Comment by PepperCode1** [comment] 2022-08-21 21:43
You are mostly correct. Inspecio and old versions of Ok Zoomer prevent Continuity's default pack from working. However, the incompatibility was fixed on Quilt's side more than three months ago.

**Comment by Julienraptor01** [comment] 2022-08-21 22:30
Here are the versions to use when combining Quilt mods before they weren't fully moved to Quilt with Fabric
> Fabric Loader 0.13.13
> Continuity 2.0.1 (the latest one) 
> Fabric Api 0.53.4
> Inspecio 1.3.1
> OK Zoomer 5.0.0-beta.6

If some of your mods refuse to boot due to fabric API being too low you need to use [Dependency Overrides](https://fabricmc.net/wiki/tutorial:dependency_overrides) and hope it work. This usually work as many mods put the latest fabric API in their requirements but don't actually need it, however some mod might really require it and then it'll cause problems

Otherwise you can use quilt, it'll work correctly with all the latest versions

**Comment by PepperCode1** [comment] 2022-09-02 04:02
It seems you are using a custom resource pack. If said resource pack replaces the glass texture, even if it is exactly the same, the default connected textures will not be applied. Otherwise, your configuration is known to work.

**Closed as completed by PepperCode1** 2022-09-02 04:02 UTC
