### ISSUE TITLE
1.21.3 update?

### ISSUE THREAD

**Issue by NeonTempest26** [PepperCode1/Continuity#542] opened 2024-11-16 19:04 UTC
When is the 1.21.3 update coming out? It keeps crashing for me.

**Comment by ghost** [comment] 2024-11-18 01:05
in discord they have test build for 1.21.3

**Comment by mharbb** [comment] 2024-11-18 17:59
> in discord they have test build for 1.21.3

what channel in the discord

**Comment by PepperCode1** [comment] 2024-11-26 19:03
Duplicate of #533.

**Closed as not planned by PepperCode1** 2024-11-26 19:03 UTC
