### ISSUE TITLE
Mod has no effect in 1.19.2

### ISSUE THREAD

**Issue by vitphire** [PepperCode1/Continuity#164] opened 2022-08-23 16:42 UTC
My installed mods are: 
`continuity-2.0.1+1.19,jar`
`fabric-api-0.60.0+1.19.2.jar`
`sodium-fabric-mc1.19-0.4.2build.16.jar`

The resource packs screen shows (from top to bottom):
`continuity/glass_pane_culling...`
`continuity/default`
`Fabric Mods`
`Default`

Everything looks like in vanilla minecraft, i saw no connected textures. (I don't know all the textures that are supposed to be connected, but glasses, glass panes weren't)
![image](https://user-images.githubusercontent.com/61618352/186214123-bf4534d3-aa87-469d-be1d-29c2b2dbc398.png)
![image](https://user-images.githubusercontent.com/61618352/186214254-591decf3-03f2-4aed-9eb9-64c108c1f27f.png)
![image](https://user-images.githubusercontent.com/61618352/186214292-3ffb66f6-58e1-4914-a4e6-48aba56e8816.png)

**Comment by PepperCode1** [comment] 2022-08-23 16:46
Duplicate of #107.

**Closed as completed by PepperCode1** 2022-08-23 16:46 UTC
