### ISSUE TITLE
Game crashing when gravel falls

### ISSUE THREAD

**Issue by MKLEGOPRO** [PepperCode1/Continuity#257] opened 2023-06-05 21:12 UTC
So I have the latest version of Continuity mod for 1.19.4 installed and I have noticed that the game crashes whenever a block of gravel falls. I know it is this mod because of a mod I have that tells me whenever a mod makes my game crash

**Comment by YukiAyase** [comment] 2023-06-05 21:44
Do you have Sodium installed as well?
If yes, you need Indium, https://modrinth.com/mod/indium/version/1.0.15+mc1.19.4
If no, please send your log file, it can be found in .minecraft/logs, filename is "latest"

**Comment by MKLEGOPRO** [comment] 2023-06-06 18:28
I didn´t have indium. Now i do, and it works. Tanks!

**Comment by PepperCode1** [comment] 2023-07-08 15:20
Duplicate of #107.

**Closed as completed by PepperCode1** 2023-07-08 15:20 UTC
