### ISSUE TITLE
Ore + Grass = (Glowing Grass)

### ISSUE THREAD

**Issue by ardissaps** [PepperCode1/Continuity#93] opened 2022-05-13 08:59 UTC
Grass with Ore Connectet not render correctly with glowing ore shader, the grass glowing like the ore. But it works fine if connected with stone (only grass glow which look so wrong).

**Comment by PepperCode1** [comment] 2022-05-14 18:16
Likely a duplicate of #65, but this issue is not very clear so I am not sure. Please confirm.

**Comment by ardissaps** [comment] 2022-05-14 22:53
> Likely a duplicate of #65, but this issue is not very clear so I am not sure. Please confirm.

Ah yes thats it, sorry, it glow like that, only on grass vs ore tho. other no problem, probably problem on the texture pack itself?

**Closed as completed** 2022-05-15 17:35 UTC
