### ISSUE TITLE
Glass panes disappear when looking through glass panes, only when their Y value is higher.

### ISSUE THREAD

**Issue by TheScienceNerd** [PepperCode1/Continuity#287] opened 2023-07-23 19:15 UTC
So I just got the mod cause it was exactly what I was looking for to really tidy up my house.
I looked through 1 window into the other, and I noticed that the window behind the one I was looking through, all glass panes that were higher in elevation than my POV would disappear from view.
![image](https://github.com/PepperCode1/Continuity/assets/67557526/ddd81aca-a95e-44fc-a1f1-2324140b4ab1)
![image](https://github.com/PepperCode1/Continuity/assets/67557526/38902f19-5c52-492c-842b-0b66328886b2)

Whats weirder is some angles, you can get the further glass pane to only show the top half but not the bottom half with this.
![image](https://github.com/PepperCode1/Continuity/assets/67557526/cc2e7045-be99-4403-b230-be9cd655f7da)

**Comment by ImGRUI** [comment] 2023-07-23 19:22
It's a sodium known issue and not related to Continuity.

**Comment by PepperCode1** [comment] 2023-07-23 19:22
Duplicate of CaffeineMC/sodium-fabric#38. Not a Continuity issue.

**Closed as completed by PepperCode1** 2023-07-23 19:22 UTC
