### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by AlmightyAlex** [PepperCode1/Continuity#345] opened 2023-12-05 14:26 UTC
its making my game crash

**Comment by YukiAyase** [comment] 2023-12-05 14:32
Please send your log file located on .minecraft/logs, filename is "latest"

**Comment by AlmightyAlex** [comment] 2023-12-05 14:44
[latest.log](https://github.com/PepperCode1/Continuity/files/13561538/latest.log)

**Comment by YukiAyase** [comment] 2023-12-05 14:46
Install [Indium](https://modrinth.com/mod/indium/version/1.0.27+mc1.20.1)


Duplicate of https://github.com/PepperCode1/Continuity/issues/107

**Comment by AlmightyAlex** [comment] 2023-12-05 14:47
okk

**Comment by JaaiDead** [comment] 2023-12-08 06:46
https://pastebin.com/ACS2rm2P
i have a very weird error and cilent crashing
with the fabric api
it happens exactly when i brake a sand block which a another sand block on top as a falling entity

**Comment by JaaiDead** [comment] 2023-12-08 06:47
Also to note indium is not installed since its not updated to sodium 0.5.4

**Comment by PepperCode1** [comment] 2023-12-08 06:53
Continuity will not magically work with Sodium just because Indium is not updated. No Indium means you will crash.

**Closed as completed by PepperCode1** 2023-12-08 06:53 UTC
