### ISSUE TITLE
Crash apparently related to Falling Sand Entity rendering.

### ISSUE THREAD

**Issue by AstralOrdana** [PepperCode1/Continuity#199] opened 2023-01-01 21:15 UTC
While using Continuity 2.0.1 for 1.19.2 Fabric, I am getting the crash detailed at the bottom of this log.
The crash seems to occur when loading new chunks that presumably contain blocks that fall after being loaded, causing the intermittent crashes. 

```
net.minecraft.ReportedException: Rendering entity in world
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.render(EntityRenderDispatcher.java:172) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.client.renderer.LevelRenderer.renderEntity(LevelRenderer.java:1568) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.client.renderer.LevelRenderer.renderLevel(LevelRenderer.java:1316) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.client.renderer.GameRenderer.renderLevel(GameRenderer.java:1039) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:816) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1177) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:768) [minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.client.main.Main.run(Main.java:244) [minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [minecraft-project-@fabric-merged-named.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:217) [architectury-transformer-5.2.72-runtime.jar:5.2.72]
Caused by: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:19) ~[continuity-2.0.1+1.19-64b5720b4b825f21.jar:?]
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:70) ~[continuity-2.0.1+1.19-64b5720b4b825f21.jar:?]
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10) ~[continuity-2.0.1+1.19-64b5720b4b825f21.jar:?]
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305) ~[?:?]
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195) ~[?:?]
	at java.lang.ThreadLocal.get(ThreadLocal.java:172) ~[?:?]
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18) ~[continuity-2.0.1+1.19-64b5720b4b825f21.jar:?]
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16) ~[continuity-2.0.1+1.19-64b5720b4b825f21.jar:?]
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10) ~[continuity-2.0.1+1.19-64b5720b4b825f21.jar:?]
	at net.minecraft.client.renderer.entity.FallingBlockRenderer.handler$zze000$beforeRenderModel(FallingBlockRenderer.java:518) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.client.renderer.entity.FallingBlockRenderer.render(FallingBlockRenderer.java:45) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.client.renderer.entity.FallingBlockRenderer.render(FallingBlockRenderer.java:17) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.render(EntityRenderDispatcher.java:141) ~[minecraft-project-@fabric-merged-named.jar:?]
	... 13 more
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-01-01 15:09:04
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:19)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:70)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.client.renderer.entity.FallingBlockRenderer.handler$zze000$beforeRenderModel(FallingBlockRenderer.java:518)
	at net.minecraft.client.renderer.entity.FallingBlockRenderer.render(FallingBlockRenderer.java:45)
	at net.minecraft.client.renderer.entity.FallingBlockRenderer.render(FallingBlockRenderer.java:17)
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.render(EntityRenderDispatcher.java:141)
	at net.minecraft.client.renderer.LevelRenderer.renderEntity(LevelRenderer.java:1568)
	at net.minecraft.client.renderer.LevelRenderer.renderLevel(LevelRenderer.java:1316)
	at net.minecraft.client.renderer.GameRenderer.renderLevel(GameRenderer.java:1039)
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:816)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1177)
	at net.minecraft.client.Minecraft.run(Minecraft.java:768)
	at net.minecraft.client.main.Main.run(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:217)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:19)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:70)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.client.renderer.entity.FallingBlockRenderer.handler$zze000$beforeRenderModel(FallingBlockRenderer.java:518)
	at net.minecraft.client.renderer.entity.FallingBlockRenderer.render(FallingBlockRenderer.java:45)
	at net.minecraft.client.renderer.entity.FallingBlockRenderer.render(FallingBlockRenderer.java:17)
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.render(EntityRenderDispatcher.java:141)
	at net.minecraft.client.renderer.LevelRenderer.renderEntity(LevelRenderer.java:1568)
	at net.minecraft.client.renderer.LevelRenderer.renderLevel(LevelRenderer.java:1316)
	at net.minecraft.client.renderer.GameRenderer.renderLevel(GameRenderer.java:1039)

-- Entity being rendered --
Details:
	Entity Type: minecraft:falling_block (net.minecraft.world.entity.item.FallingBlockEntity)
	Entity ID: 422
	Entity Name: Falling Block
	Entity's Exact location: -560.50, 46.00, -531.50
	Entity's Block location: World: (-561,46,-532), Section: (at 15,14,12 in -36,2,-34; chunk contains blocks -576,-64,-544 to -561,319,-529), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,-64,-1024 to -513,319,-513)
	Entity's Momentum: 0.00, -0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Immitating BlockState: Block{minecraft:gravel}
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.render(EntityRenderDispatcher.java:141)
	at net.minecraft.client.renderer.LevelRenderer.renderEntity(LevelRenderer.java:1568)
	at net.minecraft.client.renderer.LevelRenderer.renderLevel(LevelRenderer.java:1316)
	at net.minecraft.client.renderer.GameRenderer.renderLevel(GameRenderer.java:1039)
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:816)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1177)
	at net.minecraft.client.Minecraft.run(Minecraft.java:768)
	at net.minecraft.client.main.Main.run(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:217)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.FallingBlockRenderer@5716c72f
	Location: -35.05,19.26,-35.47 - World: (-36,19,-36), Section: (at 12,3,12 in -3,1,-3; chunk contains blocks -48,-64,-48 to -33,319,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Rotation: 0.0
	Delta: 0.21999872
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.render(EntityRenderDispatcher.java:141)
	at net.minecraft.client.renderer.LevelRenderer.renderEntity(LevelRenderer.java:1568)
	at net.minecraft.client.renderer.LevelRenderer.renderLevel(LevelRenderer.java:1316)
	at net.minecraft.client.renderer.GameRenderer.renderLevel(GameRenderer.java:1039)
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:816)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1177)
	at net.minecraft.client.Minecraft.run(Minecraft.java:768)
	at net.minecraft.client.main.Main.run(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:217)

-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Player244'/397, l='ClientLevel', x=-525.45, y=25.12, z=-496.03]]
	Chunk stats: 1024, 78
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,72,32), Section: (at 0,8,0 in 0,4,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 384073 game time, 59448 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.fillReportDetails(ClientLevel.java:453)
	at net.minecraft.client.Minecraft.fillReport(Minecraft.java:2341)
	at net.minecraft.client.Minecraft.run(Minecraft.java:787)
	at net.minecraft.client.main.Main.run(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:217)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Moonlight Generated Pack, Blooming+Blocks+1.19.2-2.1 (1).zip

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 833670984 bytes (795 MiB) / 3286237184 bytes (3134 MiB) up to 4215275520 bytes (4020 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA Quadro T1000
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1fb9
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1700
	Graphics card #1 name: Intel(R) UHD Graphics 630
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x3e9b
	Graphics card #1 versionInfo: DriverVersion=30.0.101.1404
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 28786.96
	Virtual memory used (MB): 20541.99
	Swap memory total (MB): 12707.26
	Swap memory used (MB): 1271.51
	JVM Flags: 0 total; 
	Fabric Mods: 
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 2.0.1+1.19
		disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		emi: EMI 0.5.0+1.19.2
		fabric-api: Fabric API 0.70.0+1.19.2
		fabric-api-base: Fabric API Base 0.4.14+6e0787e690
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.13+93d8cb8290
		fabric-biome-api-v1: Fabric Biome API (v1) 9.0.21+4d0d570390
		fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.23+c6af733c90
		fabric-client-tags-api-v1: Fabric Client Tags 1.0.4+b35fea8390
		fabric-command-api-v2: Fabric Command API (v2) 2.1.10+93d8cb8290
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+7c6cd14d90
		fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+27265b3490
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.4+ad31814d90
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.34+0d0f210290
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.3+9244241690
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.32+4d0d570390
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
		fabric-gametest-api-v1: Fabric Game Test API (v1) 1.1.6+4d0d570390
		fabric-item-api-v1: Fabric Item API (v1) 1.6.2+fa140d5990
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.37+9244241690
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.24+aaaf9d3390
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.3+1b46dc7890
		fabric-loot-api-v2: Fabric Loot API (v2) 1.1.11+83a8659290
		fabric-message-api-v1: Fabric Message API (v1) 5.0.6+93d8cb8290
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.22+33fbc73890
		fabric-models-v0: Fabric Models (v0) 0.3.20+c6af733c90
		fabric-networking-api-v1: Fabric Networking API (v1) 1.2.9+6e0787e690
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.4+4d0d570390
		fabric-particles-v1: Fabric Particles (v1) 1.0.13+4d0d570390
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.30+9244241690
		fabric-renderer-api-v1: Fabric Renderer API (v1) 1.1.1+6e0787e690
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.18+aeb40ebe90
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.18+6e0787e690
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.10+4d0d570390
		fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+08b73de490
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.31+4d0d570390
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.5+1cc24b1b90
		fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
		fabric-textures-v0: Fabric Textures (v0) 1.0.23+aeb40ebe90
		fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.4+4d0d570390
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabricloader: Fabric Loader 0.14.12
		generated_a610f0a: Generated Mod (Please Ignore) 1.0.0
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.0.6
		moonlight: Moonlight 1.19.2-2.1.4
		mousetweaks: Mouse Tweaks 2.22
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.19.2-build.59
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.11+mc1.19.2-build.68
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		underground_overhaul: Underground Overhaul 1.19.2-1.0.0
		yet-another-config-lib: YetAnotherConfigLib 1.1.1
	Launched Version: Fabric
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) UHD Graphics 630 GL version 3.2.0 - Build 30.0.101.1404, Intel
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, Moonlight Generated Pack, file/Blooming+Blocks+1.19.2-2.1 (1).zip
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Player244'/397, l='ServerLevel[Diamond Check]', x=-525.45, y=25.12, z=-496.03]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
```

**Comment by PepperCode1** [comment] 2023-01-01 21:24
Duplicate of #107; Install Indium.

**Closed as completed by PepperCode1** 2023-01-01 21:24 UTC
