### ISSUE TITLE
bug error loading texture pack

### ISSUE THREAD

**Issue by TRemill** [PepperCode1/Continuity#304] opened 2023-08-15 05:50 UTC
[10:25:03] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.ExceptionInInitializerError
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
	at me.pepperbell.continuity.client.resource.ModelWrappingHandler.wrap(ModelWrappingHandler.java:48) ~[continuity-3.0.0-beta.3+1.20.1.jar:?]
	at me.pepperbell.continuity.client.resource.ModelWrappingHandler.lambda$init$0(ModelWrappingHandler.java:61) ~[continuity-3.0.0-beta.3+1.20.1.jar:?]
	at net.fabricmc.fabric.impl.client.model.loading.ModelLoaderPluginContextImpl.lambda$new$6(ModelLoaderPluginContextImpl.java:97) ~[fabric-model-loading-api-v1-1.0.+709a987177-b30bbad4e291d417.jar:?]
	at net.fabricmc.fabric.impl.client.model.loading.ModelLoadingEventDispatcher.modifyModelAfterBake(ModelLoadingEventDispatcher.java:291) ~[fabric-model-loading-api-v1-1.0.+709a987177-b30bbad4e291d417.jar:?]
	at net.minecraft.class_1088$class_7778.redirect$bdp000$fabric-model-loading-api-v1$invokeModifyAfterBake(class_1088.java:560) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088$class_7778.method_45873(class_1088.jav
	at net.minecraft.class_807.method_4753(class_807.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_816.method_4753(class_816.java:89) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088$class_7778.redirect$bdp000$fabric-model-loading-api-v1$invokeModifyAfterBake(class_1088.java:558) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088$class_7778.method_45873(class_1088.java:426) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088.method_45877(class_1088.java:188) ~[client-intermediary.jar:?]
	at java.util.HashMap$KeySet.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_1088.method_45876(class_1088.java:185) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_45883(class_1092.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_45885(class_1092.java:92) ~[client-intermediary.jar:?]
	... 7 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.materialFinder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at me.pepperbell.continuity.client.util.RenderUtil.lambda$static$0(RenderUtil.java:34) ~[continuity-3.0.0-beta.3+1.20.1.jar:?]
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(Unknown Source) ~[?:?]
	at java.lang.ThreadLocal.setInitialValue(Unknown Source) ~[?:?]
	at java.lang.ThreadLocal.get(Unknown Source) ~[?:?]
	at me.pepperbell.continuity.client.util.RenderUtil.getMaterialFinder(RenderUtil.java:59) ~[continuity-3.0.0-beta.3+1.20.1.jar:?]
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.<clinit>(EmissiveBakedModel.java:36) ~[continuity-3.0.0-beta.3+1.20.1.jar:?]
	at me.pepperbell.continuity.client.resource.ModelWrappingHandler.wrap(ModelWrappingHandler.java:48) ~[continuity-3.0.0-beta.3+1.20.1.jar:?]
	at me.pepperbell.continuity.client.resource.ModelWrappingHandler.lambda$init$0(ModelWrappingHandler.java:61) ~[continuity-3.0.0-beta.3+1.20.1.jar:?]
	at net.fabricmc.fabric.impl.client.model.loading.ModelLoaderPluginContextImpl.lambda$new$6(ModelLoaderPluginContextImpl.java:97) ~[fabric-model-loading-api-v1-1.0.+709a987177-b30bbad4e291d417.jar:?]
	at net.fabricmc.fabric.impl.client.model.loading.ModelLoadingEventDispatcher.modifyModelAfterBake(ModelLoadingEventDispatcher.java:291) ~[fabric-model-loading-api-v1-1.0.+709a987177-b30bbad4e291d417.jar:?]
	at net.minecraft.class_1088$class_7778.redirect$bdp000$fabric-model-loading-api-v1$invokeModifyAfterBake(class_1088.java:560) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088$class_7778.method_45873(class_1088.java:426) ~[client-intermediary.jar:?]
	at net.minecraft.class_807.method_4753(class_807.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_816.method_4753(class_816.java:89) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088$class_7778.redirect$bdp000$fabric-model-loading-api-v1$invokeModifyAfterBake(class_1088.java:558) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088$class_7778.method_45873(class_1088.java:426) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088.method_45877(class_1088.java:188) ~[client-intermediary.jar:?]
	at java.util.HashMap$KeySet.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_1088.method_45876(class_1088.java:185) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_45883(class_1092.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_45885(class_1092.java:92) ~[client-intermediary.jar:?]
	... 7 more

full log file:
[2023-08-15-6.log.gz](https://github.com/PepperCode1/Continuity/files/12341545/2023-08-15-6.log.gz)

The problem manifests itself only with your mod and the use of this texture pack:
[KSEPSPv8.2-F0RZEL.zip](https://github.com/PepperCode1/Continuity/files/12341550/KSEPSPv8.2-F0RZEL.zip)

Version Minecraft: 1.20.1
Version Continuity: 3.0.0-beta.3

**Comment by PepperCode1** [comment] 2023-08-15 11:16
You did not provide your mod list but realistically the only way this could happen is if you did not install Indium. Duplicate of #107.

**Closed as completed by PepperCode1** 2023-08-15 11:16 UTC
