### ISSUE TITLE
3.0.0-beta.2+1.20 game crashes after gravel falls

### ISSUE THREAD

**Issue by NuggetPudding** [PepperCode1/Continuity#265] opened 2023-06-18 18:38 UTC
I have both sodium and indium installed
![image](https://github.com/PepperCode1/Continuity/assets/136999410/2100dbc7-8631-4135-8485-c08f98e63a2f)

**Comment by NuggetPudding** [comment] 2023-06-18 18:40
nevermind I didn't have indium installed

**Comment by NuggetPudding** [comment] 2023-06-18 18:41
I forgot to put it in the mods folder

**Comment by Subroutine7901** [comment] 2023-06-27 02:11
Exact same issue, down to the indium part.

**Comment by YukiAyase** [comment] 2023-06-27 02:15
> Exact same issue, down to the indium part.

**Please create your own thread which includes your latest log file and a screenshot of your mods folder if you're experiencing crashes**
_And please do also avoid necroing inactive threads_

**Comment by Subroutine7901** [comment] 2023-06-27 02:18
Got it, sorry.

**Comment by ghost** [comment] 2023-07-08 15:15
I have a same problem

**Comment by PepperCode1** [comment] 2023-07-08 15:20
Duplicate of #107, as always.

**Closed as completed by PepperCode1** 2023-07-08 15:20 UTC
