### ISSUE TITLE
Incompatible with 3D Default resourcepack and Fabric API 0.80.0+

### ISSUE THREAD

**Issue by W2D3F1X2** [PepperCode1/Continuity#276] opened 2023-07-09 03:28 UTC
When I enter a world or server, the game either gets stuck or crashes. I have to install Fabric api 0.79.0 to use Continuity and 3D Default at the same time.
Minecraft 1.19.4, Fabric loader 0.14.21, Fabric api 0.80.0, 0.83.0 and 0.85.0 respectively, Continuity 3.0.0-beta.2, 3D Default 1.8.0. [crash-2023-07-09_10.08.12-client.txt](https://github.com/PepperCode1/Continuity/files/11994320/crash-2023-07-09_10.08.12-client.txt)

**Comment by PepperCode1** [comment] 2023-07-09 04:10
Duplicate of #253.

**Closed as completed by PepperCode1** 2023-07-09 04:10 UTC
