### ISSUE TITLE
Emissive textures Z-fighting

### ISSUE THREAD

**Issue by antieksi** [PepperCode1/Continuity#292] opened 2023-08-01 14:26 UTC
![изображение](https://github.com/PepperCode1/Continuity/assets/95758843/c66325d7-e85b-4067-ba65-74492777ced6)

The resourcepack containing emissive textures here is [Glowing](https://modrinth.com/resourcepack/glowing).

**Comment by antieksi** [comment] 2023-08-01 14:33
I guess it can be seen better on a video.

https://i.imgur.com/v23d4HL.mp4

**Comment by DDunda** [comment] 2023-08-04 02:57
I am also having the same issue, and with some testing I've found the z-fighting seems to occur on certain corners. The behaviour occurs on multiple packs with emissive textures.

A flat 5x5 plane:
![image](https://github.com/PepperCode1/Continuity/assets/50138952/6ee9c36f-93a7-4c22-b78e-6d8ff6295d18)

The same plane with a block placed in the center (z-fighting highlighted):
![image](https://github.com/PepperCode1/Continuity/assets/50138952/3d346182-4091-45b3-afe5-8984cf45acf6)

**Comment by Wikinger8** [comment] 2023-08-05 19:44
I have the same problem no other mods than Sodium Indium and Continuity

**Comment by JackiTacki** [comment] 2023-08-07 17:50
+1

I thought I was going insane and it was there the whole time. Seems its new!

**Comment by Wikinger8** [comment] 2023-08-07 19:26
> +1
> 
> I thought I was going insane and it was there the whole time. Seems its new!

Yeah maybe the 1.20.1 versions or a sodium update or something

**Comment by Wikinger8** [comment] 2023-08-07 20:40
i think the newest indium update fixed the issue

**Comment by JackiTacki** [comment] 2023-08-08 12:51
I'll check!

**Comment by JackiTacki** [comment] 2023-08-08 12:52
Doesnt seem like it. . .

**Comment by DDunda** [comment] 2023-08-09 01:12
The issue is worse now, and different faces are affected. Up to three faces per corner can be affected.
![Emissive issue 2](https://github.com/PepperCode1/Continuity/assets/50138952/2333cf03-648d-4325-bf92-289fc37b0a5c)

It also interacts with light levels strangely (non-fighting blocks removed for clarity)
![Emissive issue 3](https://github.com/PepperCode1/Continuity/assets/50138952/41c6744f-34ca-4e0a-8d31-9d874e6e4edb)

**Comment by PepperCode1** [comment] 2023-08-09 01:19
The issue may be worsened by Sodium's compact vertex format. Regardless, it cannot really be fixed.

As a workaround, is possible to fix manually by removing pixels from the base texture that appear in the emissive texture, but this will cause those textures to look completely incorrect if emissive textures are disabled.

**Comment by DDunda** [comment] 2023-08-09 01:25
I just tried turning off smooth lighting and all Z-fighting stopped (including corner fighting), is that related to the vertex format?

**Comment by PepperCode1** [comment] 2023-08-09 02:06
No.

**Comment by JackiTacki** [comment] 2023-08-09 15:15
Smooth Lighting is the weird cause of this, It seems. Turning it off makes it work fine, But the rest of the lighting then looks worse.

**Comment by notandvm** [comment] 2023-08-09 18:29
> As a workaround, is possible to fix manually by removing pixels from the base texture that appear in the emissive texture, but this will cause those textures to look completely incorrect if emissive textures are disabled.

adding to this for anyone doing such;
blocks that naturally give off light seem to be unaffected (enchanting tables, crying obsidian, etc) 
it's strictly non-light blocks that cause the z-fighting, which helps to slightly reduce the load for editing bigger emissive packs

this can be best seen with redstone ore; when unlit z-fighting is present, though when lit it's as expected (no z-fighting)

**Comment by JackiTacki** [comment] 2023-08-09 18:45
This issue used to not exist. It seems a sudden affliction.

**Comment by JackiTacki** [comment] 2023-08-09 18:49
Until this situation gets resolved, 3D ore packs using emissives may be unuseable.

I found a way to keep the emissives without the 3d textures.

**Comment by antieksi** [comment] 2023-08-09 18:51
> As a workaround, is possible to fix manually by removing pixels from the base texture that appear in the emissive texture, but this will cause those textures to look completely incorrect if emissive textures are disabled.

Is it possible to not render those pixels that are covered with emissive texture? AND to do it only when emissive textures are enabled.

**Comment by notandvm** [comment] 2023-08-09 18:52
> This issue used to not exist. It seems a sudden affliction.

if i had to guess the recent sodium (& related (indium, iris)) updates caused it since downgrading back to previous versions leads to it being normal again

which isn't surprising given the sodium update broke a _lot_ of mods, even some that you wouldn't expect like mod menu at least with what i've run into

**Comment by JackiTacki** [comment] 2023-08-09 22:49
Hoping this gets fixed. . .

Im still having issues, And dont feel like having to use shaders constantly for ores. For now I'll just use Reimagined, But F for my FPS.

**Comment by JackiTacki** [comment] 2023-08-19 22:09
Still could use an update on how to resolve this. . .

**Comment by ItsSunnyMonster** [comment] 2023-08-19 22:18
Do we have any ideas as to what is causing the issue?

**Comment by DDunda** [comment] 2023-08-21 10:07
> Do we have any ideas as to what is causing the issue?

It appears to be related to smooth shading as the z-fighting stops when you disable it

**Comment by JackiTacki** [comment] 2023-08-23 09:28
Confirmed. Smooth Lighting is the seeming cause

**Comment by JackiTacki** [comment] 2023-08-25 14:50
Hopefully this can get a resolve. This is getting more annoying each time I have to deal with it. Sadge. . .

**Comment by ItsSunnyMonster** [comment] 2023-09-09 22:20
Any updates?

**Comment by PepperCode1** [comment] 2023-09-09 22:40
No

**Comment by JackiTacki** [comment] 2023-09-18 11:50
Yeesh. This may never get fixed. Depressing too. . .

**Comment by 7777777-4547** [comment] 2023-11-12 09:28
A video from a previous test.

https://github.com/PepperCode1/Continuity/assets/83630775/a45a23f5-b931-4113-9e2a-4c173876d6e9

**Comment by AlphaCraft9658** [comment] 2023-11-26 16:22
This bug has been bugging me for quite some time. Any new information on this bug?

**Comment by BlueJayofEvil** [comment] 2023-11-28 04:08
MoreMcmeta seems to have fixed this same issue in their emissive plugin. Might be worth checking how they worked around the issue.
https://github.com/MoreMcmeta/emissive-plugin/issues/10

**Comment by JuceInUse** [comment] 2023-11-29 22:14
I tried patching it by just removing the textures under the emissive layer manually and, uh... that didn't work lol

![image](https://github.com/PepperCode1/Continuity/assets/85078618/ec2563ec-2447-4ae4-8fe0-70fd69c34f5a)

I hope to see an eventual real fix to this bug!

**Comment by perilstar** [comment] 2023-12-07 02:35
emissive-plugin seems to have fixed this by offsetting all the vertices of the overlay by a tiny amount.

**Comment by PepperCode1** [comment] 2023-12-07 06:14
The underlying cause of the issue has been found. It is explained below. This issue only happens with Sodium and Indium.

Sodium changes the vertex order on certain quads based on their AO and lightmap values to fix a vanilla bug where smooth lighting looks different in different directions (https://bugs.mojang.com/browse/MC-136302). Indium inherits this fix by using logic similar to Sodium's in its own pipeline. The emissive z-fighting happens when the base quad and the emissive quad have different orientations; that is, one has a normal vertex order and the other has a flipped vertex order.

There is no simple fix to this issue. Any currently known fix is imperfect and may require adding a configuration option and may impact visuals (but not performance). A future release of Continuity may include a solution.

**Comment by antieksi** [comment] 2023-12-07 07:57
Even though this is a pretty tough bug, you continue working on this mod, and you do it for nothing. Just wanted to thank you for your work. Huge respect

**Comment by AlphaCraft9658** [comment] 2023-12-07 21:23
> The underlying cause of the issue has been found. It is explained below. This issue only happens with Sodium and Indium.
> 
> Sodium changes the vertex order on certain quads based on their AO and lightmap values to fix a vanilla bug where smooth lighting looks different in different directions (https://bugs.mojang.com/browse/MC-136302). Indium inherits this fix by using logic similar to Sodium's in its own pipeline. The emissive z-fighting happens when the base quad and the emissive quad have different orientations; that is, one has a normal vertex order and the other has a flipped vertex order.
> 
> There is no simple fix to this issue. Any currently known fix is imperfect and may require adding a configuration option and may impact visuals (but not performance). A future release of Continuity may include a solution.

It seems like this but has been resolved in vanilla, so Sodium and Indium shouldn't have to implement their own fix. Correct me if I'm wrong.

**Comment by PepperCode1** [comment] 2023-12-07 21:26
No, it is not fixed in vanilla. The issue I linked may have been a duplicate. Here is a report of the same issue that is not closed.
https://bugs.mojang.com/browse/MC-138211

**Comment by dylanxyz** [comment] 2023-12-19 13:23
Any updates on this? I can also confirm that this happens on Neoforge `47.1.79` with the Sinytra Connector mod.

**Comment by Lolothepro** [comment] 2024-01-12 17:38
Note: a fix was added in Embeddium, but is impossible to port in Sodium "the approach only works when all the quads are known up front (i.e. the way Forge works)".

**Comment by xNotLeo** [comment] 2024-05-31 07:04
Hello, I think I found a type of solution to this z fighting problem, it turns out that the mushrooms generate a level 1 light and it occurred to me that if the blocks with shiny textures generate z fighting only in the dark, what would happen if the flowers or blocks with these properties will shine? and then I found this Glowing Ores mod https://modrinth.com/mod/glore which literally lets us do this, so I installed it and in the mods folder 2 files are generated that allow us to modify the brightness level of the blocks and blocks that will have these properties, for example if the diamond ore has a shiny texture we add it to the file and give it a brightness level of 1, this way it will NEVER AGAIN have the z Fighting error :)
(I'm using Google Translate so sorry for my English)
![Captura de pantalla 2024-05-31 011559](https://github.com/PepperCode1/Continuity/assets/142868666/46887c91-cb68-49b6-a326-84dc81615bb0)

**Comment by antieksi** [comment] 2024-05-31 07:12
Do you propose just adding the emissive texture to a normal one and making only its pixels to glow?

**Comment by xNotLeo** [comment] 2024-05-31 15:39
> ¿Propones simplemente agregar la textura emisiva a una normal y hacer que solo brillen sus píxel
My proposal is to give a slight level of light to the blocks with emissive textures that is practically undetectable, helping to fix the z fighting in its entirety.

**Comment by xNotLeo** [comment] 2024-05-31 15:43
![2024-05-31_10 17 45](https://github.com/PepperCode1/Continuity/assets/142868666/d353ee78-d724-415d-9368-dd174c02de3d)
![2024-05-31_10 19 11](https://github.com/PepperCode1/Continuity/assets/142868666/b479e976-aded-4afc-8425-3e2b02b3acc5)
> ¿Propone simplemente agregar la textura emisiva a una normal y hacer que solo brillen sus píxeles?

Not exactly, in reality the idea is that the block (such as a diamond ore) which has an emissive texture is added a complete block making the z fighting imperceptible to the naked eye so instead of just making the pixels with the shiny property the point is for the entire block to shine

**Comment by GalaxyGaming2000** [comment] 2024-06-17 10:46
any updates on this?

**Comment by PepperCode1** [comment] 2024-11-26 18:51
Sodium 0.6 has been released and should have resolved this issue.

**Closed as completed by PepperCode1** 2024-11-26 18:51 UTC
Labels: mod compatibility
