### ISSUE TITLE
Make a way to depend (in the mod settings) on Indium ONLY when Sodium is installed.

### ISSUE THREAD

**Issue by mrjasonn** [PepperCode1/Continuity#286] opened 2023-07-22 08:45 UTC
Please make a way to depend (in the mod settings) on Indium ONLY when Sodium is installed if possible so if people have Sodium and don't have Indium then the game will just crash instead of having weird issues.

**Comment by PepperCode1** [comment] 2023-07-22 14:49
This is mostly a duplicate of #279.

**Closed as completed by PepperCode1** 2023-07-22 14:49 UTC
