### ISSUE TITLE
[1.19] Crash with Quilted Fabric API

### ISSUE THREAD

**Issue by forkiesassds** [PepperCode1/Continuity#149] opened 2022-08-04 14:38 UTC
[crash-2022-08-04_17.35.04-client.txt](https://github.com/PepperCode1/Continuity/files/9260637/crash-2022-08-04_17.35.04-client.txt)
If needed, this issue can be forwarded to the Quilt developers.

**Comment by PepperCode1** [comment] 2022-08-04 15:24
Duplicate of #107; install Indium.

**Closed as not planned by PepperCode1** 2022-08-04 15:24 UTC
