### ISSUE TITLE
On re-entering world texture is resetted to default

### ISSUE THREAD

**Issue by mineketchup** [PepperCode1/Continuity#565] opened 2024-12-13 21:17 UTC
Modloader: 
- Fabric

Mod Version: 
- 3.0.0 
with Minecraft ver. 1.21, 1.21.1, 1.21.3

Installed Mods: 
- Continuity; 
- Fabric-Api
(ver1.102.0 with 1.21,
ver1.110.0 with 1.21.1, 
ver 1.112.0 with 1.21.3)

Texture Pack:
- Xali's Enhanced Vanilla

Explanation:
- Using the renaming method with Barrels, texture gets changed correctly (for example renaming a Barrel to 'Acacia Barrel Apple' gives the corresponding block). But exiting once the world and re-entering, the texture of every placed barrel gets reverted to normal default one
- Entering the world while using Optifine shows the correct textures
- The same issue happens when disabling and enabling again Xali's texture pack, so I have to place again the textured blocks

Placing Blocks
![2024-12-13_22 13 05](https://github.com/user-attachments/assets/8502e777-5487-4f88-a01a-8406e129d44f)
Re-entering world resets every texture
![2024-12-13_22 13 16](https://github.com/user-attachments/assets/be923863-12f5-4f1a-b78d-35cc34a07b9d)

 Other features work as intended (except bookshelf renaming method but it's not like this bug where it works first and breaks on world reload)

**Comment by PepperCode1** [comment] 2024-12-13 21:19
Duplicate of #449.

**Closed as not planned by PepperCode1** 2024-12-13 21:19 UTC

**Comment by mineketchup** [comment] 2024-12-13 21:20
Sorry. I thought I checked extensively, it wasn't my intention to create a duplicate
