### ISSUE TITLE
Null Pointer causing game crash when world is loaded

### ISSUE THREAD

**Issue by kineticV** [PepperCode1/Continuity#168] opened 2022-09-11 03:30 UTC
This error causes the client to crash when entering my world. I haven't had issues with Continuity for a long while, and it worked in this test world in creative for maybe 20 minutes until the error occurred, and now it always happens when entering the world. I can only reproduce the error in that one world. Removing Continuity fixes the problem.

> java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.model.SpriteFinder.find(net.fabricmc.fabric.api.renderer.v1.mesh.QuadView, int)" because the return value of "me.pepperbell.continuity.client.util.RenderUtil.getSpriteFinder()" is null

Here is the full error log:

https://pastebin.com/Qih7QJYp

**Comment by PepperCode1** [comment] 2022-09-11 05:05
Duplicate of #120.

**Closed as completed by PepperCode1** 2022-09-11 05:05 UTC
