### ISSUE TITLE
Glass panes don't work with water

### ISSUE THREAD

**Issue by Bloopything** [PepperCode1/Continuity#137] opened 2022-07-03 07:24 UTC
![2022-07-03_17 21 23](https://user-images.githubusercontent.com/108606801/177029654-8035c523-0169-4e89-bcfc-d6d7c301c806.png)

**Comment by PepperCode1** [comment] 2022-07-03 10:06
Duplicate of CaffeineMC/sodium-fabric#38.

**Closed as not planned by PepperCode1** 2022-07-03 10:06 UTC
