### ISSUE TITLE
Bump version of RessourcePack for MC1.20.3+

### ISSUE THREAD

**Issue by Athar42** [PepperCode1/Continuity#363] opened 2024-01-17 19:54 UTC
Please, update the RP specification to version 22 so it's not "marked in red" with a big warning.

I'll not send any logs, and I already did this change on my end (would have made a PR if a 1.20 branch was existing, but that's not the case here)

Before the change : 
![297495490-83175bf4-75ed-4644-aa91-702ed5b33e8b-1](https://github.com/PepperCode1/Continuity/assets/44590042/e462a7c1-aba2-40eb-a9ca-a43951799ac2)

After the change : 
![image](https://github.com/PepperCode1/Continuity/assets/44590042/278948f4-01d5-441f-a6a0-0d88fd0af44c)

And it's working just fine : 
![image](https://github.com/PepperCode1/Continuity/assets/44590042/e6ebe554-f646-49b2-a7f4-ab5db8831133)

Change to be made in both RP located in : 
- resourcepacks\default
- resourcepacks\glass_pane_culling_fix
File to be modified : pack.mcmeta
Change from : 
"pack_format": 18,
to
"pack_format": 22,

**Comment by PepperCode1** [comment] 2024-01-17 19:55
Duplicate of #355

**Closed as completed by PepperCode1** 2024-01-17 19:55 UTC

**Comment by EditChris** [comment] 2024-01-23 00:54
I know this has been closed already, but to avoid opening a new issue for the same topic I'll just send it here. I'd suggest to add this line below the pack_format one to add backwards compatibility with future versions of the game, so the red mark doesn't appear anymore and you don't have to update the resource packs constantly with every tiny change Mojang does, but only when they really need it:

    "supported_formats": {
      "min_inclusive": 22,
      "max_inclusive": 999
    },

Tried it myself loading a modified version of these two resource packs with that change in the latest build of Continuity available in Modrinth. Works as desired.

**Comment by Canes2023** [comment] 2024-04-08 21:07
I'm aware this closed already, but where can we edit those lines? I'm having the same issue where the packs are outdated.
