### ISSUE TITLE
Crash in 1.19 with iris and Complementary Shaders

### ISSUE THREAD

**Issue by KamilBaczkowski** [PepperCode1/Continuity#132] opened 2022-06-25 08:06 UTC
When I place a sand block that would fall, the game crashes. It doesn't crash without shaders

Mods:
  [✔️] cloth-config-7.0.72-fabric
  [✔️] continuity-2.0.0+1.19
  [✔️] fabric-api-0.56.3+1.19
  [✔️] iris-mc1.19-1.2.5
  [✔️] phosphor-fabric-mc1.19.x-0.8.1
  [✔️] sodium-fabric-mc1.19-0.4.2+build.16

Shader pack: ComplementaryShaders_v4.5

**Comment by PepperCode1** [comment] 2022-06-25 08:09
Duplicate of #107.

**Closed as not planned by PepperCode1** 2022-06-25 08:09 UTC
