### ISSUE TITLE
CITs and emissive textures

### ISSUE THREAD

**Issue by bitfoxWasTaken** [PepperCode1/Continuity#197] opened 2022-12-28 21:56 UTC
CITs with custom item models does not support emissive textures
![2022-12-28_22 23 18](https://user-images.githubusercontent.com/92230702/209876235-2c84ffe9-4016-4a99-b8b9-1737a5a36e91.png)
Optifine for reference
![2022-12-28_22 54 44](https://user-images.githubusercontent.com/92230702/209876245-28f05a6d-6311-4934-a8d5-6d5a4d7de97f.png)

**Comment by PepperCode1** [comment] 2022-12-28 21:56
Duplicate of #140.

**Closed as completed by PepperCode1** 2022-12-28 21:56 UTC

**Comment by bitfoxWasTaken** [comment] 2022-12-28 22:04
I've got CIT resewn, Sodium and Puzzle installed. Still not working.

**Comment by Julienraptor01** [comment] 2022-12-28 22:05
That's due to this issue
https://github.com/SHsuperCM/CITResewn/issues/149

**Comment by bitfoxWasTaken** [comment] 2022-12-28 22:11
> That's due to this issue [SHsuperCM/CITResewn#149](https://github.com/SHsuperCM/CITResewn/issues/149)

Thank you, is there currently no workaround?
