### ISSUE TITLE
Cannot set Vanila Tweaks Resourcepack

### ISSUE THREAD

**Issue by futag** [PepperCode1/Continuity#170] opened 2022-09-22 00:51 UTC
Some selector from vanila tweaks resourcepack, make this set resourepack failed when install continuity mod even though the continuity resousespack hasn't been installed yet

**Comment by futag** [comment] 2022-09-22 00:53
Resource pack: [VanillaTweaks_r137394.zip](https://github.com/PepperCode1/Continuity/files/9621274/VanillaTweaks_r137394.zip)

**Comment by PepperCode1** [comment] 2022-09-22 01:06
Logs?

**Comment by yarndinasti** [comment] 2022-09-22 13:29
[2022-09-22-3.log](https://github.com/PepperCode1/Continuity/files/9626212/2022-09-22-3.log)

**Comment by futag** [comment] 2022-09-22 13:29
Logs: [2022-09-22-5.log](https://github.com/PepperCode1/Continuity/files/9626214/2022-09-22-5.log)

**Comment by PepperCode1** [comment] 2022-09-22 16:35
Duplicate of #107; install Indium.

**Closed as not planned by PepperCode1** 2022-09-22 16:35 UTC
