### ISSUE TITLE
Emissive Textures causing blocks to disappear

### ISSUE THREAD

**Issue by RocKeD** [PepperCode1/Continuity#259] opened 2023-06-11 19:52 UTC
I have Continuity
Entitity Texture Features
Indium
Iris
LambDynamicLights
Lithium
Sodium
Mod Menu
https://imgur.com/a/sQbFcLg

**Comment by PepperCode1** [comment] 2023-06-11 20:00
Which Minecraft version, which version of Continuity, and which version of Indium?

**Comment by RocKeD** [comment] 2023-06-11 20:04
Minecraft 1.19.4 running fabric 0.14.21, continuity 3.0.0-beta.2+1.19.3, Indium 1.0.18+1.19.4

**Comment by PepperCode1** [comment] 2023-06-11 20:04
Downgrade Indium to the previous version for now.

**Comment by RocKeD** [comment] 2023-06-11 20:12
Now i receive this error "Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Indium' (indium) 1.0.14+mc1.19.3 with any version that is compatible with:
		 - sodium 0.4.10+build.24
Unmet dependency listing:
	 - Mod 'Indium' (indium) 1.0.14+mc1.19.3 requires version 0.4.9 of mod 'Sodium' (sodium), but only the wrong version is present: 0.4.10+build.24!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
"
Any when I downgrade everything else I get a game crash with no info.

**Comment by dude4123** [comment] 2023-06-13 04:21
use Indium version 1.0.15 for Minecraft 1.19.4
Although I have no idea if it solves the problem, I'm also looking for solutions

**Comment by PepperCode1** [comment] 2023-07-08 15:52
Duplicate of #253. That issue now tracks the incompatibility with both Indigo and Indium.

**Closed as completed by PepperCode1** 2023-07-08 15:52 UTC
