### ISSUE TITLE
Continuity doesn't work in 1.18.2 with sodium and indium

### ISSUE THREAD

**Issue by KB-Q** [PepperCode1/Continuity#80] opened 2022-03-30 15:31 UTC
Continuity doesn't work in 1.18.2, with sodium and indium. Glass and panes are not connecting.

Mod list:
[MC modlist Mar 2022.txt](https://github.com/PepperCode1/Continuity/files/8381869/MC.modlist.Mar.2022.txt)

Logs:
[latest.log](https://github.com/PepperCode1/Continuity/files/8381818/latest.log)
[2022-03-30-2.log.gz](https://github.com/PepperCode1/Continuity/files/8381819/2022-03-30-2.log.gz)
[2022-03-30-1.log.gz](https://github.com/PepperCode1/Continuity/files/8381821/2022-03-30-1.log.gz)

Opening this new issue since the previous one got closed for some reason. Please let me know if there's a possible fix to this. Thanks in advance.

**Comment by PepperCode1** [comment] 2022-03-30 15:54
Please have a bit more patience. I cannot constantly monitor and respond to this issue tracker.
Duplicate of #79.

**Closed as completed by PepperCode1** 2022-03-30 15:54 UTC

**Comment by KB-Q** [comment] 2022-03-30 16:25
Ah no issues. My understanding with the GitHub tracker was that an issue is only closed when it is resolved. So when the previous issue got closed without resolution I thought I did something wrong, hence I created this new issue. 

Anyways take your time, and maybe reopen the previous issue since it didn't get resolved yet. Thanks.

**Comment by machiecodes** [comment] 2022-03-30 16:44
Intelligent life in the github issues 🤯🙏
