### ISSUE TITLE
使用资源包glass pane culling fix，（看图）玻璃板竖着形成夹角会导致一块边缘消失

### ISSUE THREAD

**Issue by hya21** [PepperCode1/Continuity#466] opened 2024-07-07 05:06 UTC
![2024-07-07_12 57 45](https://github.com/PepperCode1/Continuity/assets/131333746/4802ac04-6a0a-4096-8470-de17eecb2846)
使用资源包glass pane culling fix，（看图）玻璃板竖着形成夹角会导致一块边缘消失
Translation: Using the resource pack Glaspaney Kalinfix, (see picture) Forming an angle between the glass panes vertically causes a piece of edge to disappear

**Comment by PepperCode1** [comment] 2024-07-07 21:36
Duplicate of #74.

**Closed as not planned by PepperCode1** 2024-07-07 21:36 UTC
