### ISSUE TITLE
Continuity's rendering is having issues.

### ISSUE THREAD

**Issue by MagmaSlime123** [PepperCode1/Continuity#358] opened 2023-12-27 19:09 UTC
Title, see the report below. Modlist is also included.

https://pastebin.com/Wg48hGVG

**Comment by YukiAyase** [comment] 2023-12-27 19:24
Install [Indium](https://modrinth.com/mod/indium)

Duplicate of https://github.com/PepperCode1/Continuity/issues/107

**Comment by MagmaSlime123** [comment] 2023-12-29 04:19
Seems MoreCulling and LambBetterGrass also hate this mod. A 4-way conflict.

https://pastebin.com/02P5Ub3Y

**Comment by YukiAyase** [comment] 2023-12-29 04:24
> Seems MoreCulling and LambBetterGrass also hate this mod. A 4-way conflict.
> 
> https://pastebin.com/02P5Ub3Y

Its MoreCulling incompatibility with latest ModernFix
Solution: remove MoreCulling
https://github.com/FxMorin/MoreCulling/issues/195

**Closed as completed** 2024-01-04 22:07 UTC
