### ISSUE TITLE
Resource Packs in Continuity are Outdated

### ISSUE THREAD

**Issue by Canes2023** [PepperCode1/Continuity#403] opened 2024-04-08 21:13 UTC
I just installed continuity and it looks great, but the resource packs are outdated so I'm unable to use the glass pane fix or the default continuity textures.

**Comment by Canes2023** [comment] 2024-04-08 21:15
I saw there was a similar issue that was closed already but where do we edit those lines? I believe the post was from Jan 17th.

**Comment by PepperCode1** [comment] 2024-04-08 21:17
Did you read the comments on that issue? It was closed because it was a duplicate, not because it is resolved. This is also a duplicate of #355.

**Closed as not planned by PepperCode1** 2024-04-08 21:17 UTC
