### ISSUE TITLE
Glass connecting shows incorrect textures. [1.21 Fabric]

### ISSUE THREAD

**Issue by Siloent** [PepperCode1/Continuity#482] opened 2024-08-01 20:29 UTC
I was playing my testing world when I logged out of the world to do something else. When I logged back into the world, I didn't see anything else wrong until I got out of what was going to be my slime farm. I used lime green glass to make a slime out of blocks, but when I went to go mess with the design, the blocks looked like parts of chests and shulker boxes! I later tested this for the other glass types and discovered that most, if not all of the other glass types had this same issue. Some, the regular glass in particular, didn't show up at all, even with nothing placed next to the glass. The issue itself is evident when placing down just one block of any glass type.

All the mods I have mostly follow the Fabulously Optimized mod pack's beta 1.21 version with my personal additions of Journey Map, JEI, Clumps, Jade, Leaves Be Gone, and Not Enough Animations. I have had these mods along with continuity before and no problems had occurred to my knowledge before, so this is the first time this has occurred for me. I hope this helps solve the issue.

![huge_2024-08-01_14 15 35](https://github.com/user-attachments/assets/25480558-5c44-4bbb-b651-3d39845114cb)

**Comment by Siloent** [comment] 2024-08-01 20:42
Reloading the texture pack fixes it temporarily for that session, but it still persists when logging out and then back in again.

**Comment by PepperCode1** [comment] 2024-08-01 20:53
Duplicate of #446.

**Closed as not planned by PepperCode1** 2024-08-01 20:53 UTC
