### ISSUE TITLE
Pistons crash the game when activated

### ISSUE THREAD

**Issue by AlphyiLang** [PepperCode1/Continuity#389] opened 2024-03-14 12:48 UTC

**Comment by YukiAyase** [comment] 2024-03-14 12:53
Please provide your log file located in **".minecraft/logs"**, filename is **"latest"**

**Comment by Dart2112** [comment] 2024-03-15 11:50
Not OP, but experiencing the same issue.
https://pastebin.com/mYzJUnqc
For me it happens when I trigger a piston door on my server

**Comment by YukiAyase** [comment] 2024-03-15 11:54
> Not OP, but experiencing the same issue. https://pastebin.com/mYzJUnqc For me it happens when I trigger a piston door on my server

Please do upload/send "latest" log instead of the "crash" log file
Most likely a duplicate of #107 
So please install [Indium](https://modrinth.com/mod/indium)

**Comment by Dart2112** [comment] 2024-03-15 11:57
That does seem to be the issue. Is it possible to make the mod require indium such that it won't boot without it? Like setting it as a required dependency? It worked fine without it until the pistons went off, so I didn't even think to check if my uninstalling indium was the cause.

**Comment by YukiAyase** [comment] 2024-03-15 12:15
> That does seem to be the issue. Is it possible to make the mod require indium such that it won't boot without it? Like setting it as a required dependency? It worked fine without it until the pistons went off, so I didn't even think to check if my uninstalling indium was the cause.

That I think won't be done as native Fabric Rendering API (FRAPI) support will be coming to Sodium soon *though only for the latest version of Minecraft at the time of release*, Indium is only needed if Sodium is installed as Indium is basically a compatibility layer that allows mods, such as Continuity, to make use of FRAPI while letting Sodium do its thing

And I think Pepper only supports the latest versions of Minecraft *at the time* as well

**Closed as completed** 2024-03-17 19:25 UTC
