### ISSUE TITLE
Glass isnt connecting

### ISSUE THREAD

**Issue by DalarMaximus** [PepperCode1/Continuity#356] opened 2023-12-24 07:23 UTC
i have the textures enabled. and the mod turned on in the config. I've reloaded the game and swapped texture pack loading and it doesn't work.

![image](https://github.com/PepperCode1/Continuity/assets/45615733/dcd575cc-7af6-44f1-a06c-493ec76079b5)
![image](https://github.com/PepperCode1/Continuity/assets/45615733/07b20fb8-51a2-46b4-8628-6ee9a90d0704)

**Comment by YukiAyase** [comment] 2023-12-24 07:24
Install [Indium](https://modrinth.com/mod/indium)

Duplicate of https://github.com/PepperCode1/Continuity/issues/107

**Closed as completed** 2023-12-24 07:30 UTC
