### ISSUE TITLE
How do I fix some Glass Pane faces missing?

### ISSUE THREAD

**Issue by YacuGitHub** [PepperCode1/Continuity#475] opened 2024-07-20 21:15 UTC
![image](https://github.com/user-attachments/assets/9bb1a54c-9773-416d-b566-99e7458a9dc7)

It is weird because they aren't missing until I put another glass pane on top of it... What should I do?

**Comment by Mat1212fr** [comment] 2024-07-25 15:49
Do you enable the build-in resource pack Glass Panes fix ?

**Comment by YacuGitHub** [comment] 2024-07-25 23:04
> Do you enable the build-in resource pack Glass Panes fix ?

Yes I did, but it still happens, the issue isn't present when the top layer of glass panes is the same size of the layer that's underneath (Basically a square or rectangle)

**Comment by YukiAyase** [comment] 2024-07-25 23:14
This was reported way back
And someone actually presented a fix for this
But I don't know if @PepperCode1 will implement his own fix for this in the future

**Comment by YacuGitHub** [comment] 2024-07-25 23:21
I did research inside of the other threads in the "Issues" tab with similar keywords as mine,
So I thiiink we might be talking about the same Issue, but I didn't find a solution there sadly q-p

If there is an external resourcepack I should also use, please tell me

**Comment by PepperCode1** [comment] 2024-08-01 21:05
Duplicate of #74. Enabling the glass pane culling fix pack will cause this, but not enabling it will leave horizontal lines between stacked glass panes. As stated in the comments of that issue, MoreCulling may fully resolve this issue, but I do not know what features it provides and I have not used it so this is not a personal recommendation.

**Closed as not planned by PepperCode1** 2024-08-01 21:05 UTC
