### ISSUE TITLE
Not working on 1.20.4

### ISSUE THREAD

**Issue by ShulkerSakura** [PepperCode1/Continuity#360] opened 2024-01-03 04:20 UTC
Game Version : 1.20.4
Fabric : 0.15.3
Fabric API : 0.92.0
Continuity : 3.0.0-beta.4
Cloth Config : 13.0.121
Completely no CTM texture working in game(like glass).

**Comment by YukiAyase** [comment] 2024-01-03 04:21
Please send your log file
Located on **.minecraft/logs, filename is "latest"**

**Comment by Blastshotting** [comment] 2024-01-12 21:00
I had a similar problem and do have Indium installed.
[latest.log](https://github.com/PepperCode1/Continuity/files/13923979/latest.log)

The log file showed something was disabling the built-in Continuity resourcepacks because it was built for an older Minecraft version; manually forcing them back on in the in-Minecraft resourcepack menu restored connected texture functionality.

**Comment by Athar42** [comment] 2024-01-17 12:25
I can confirm that, the ressource pack is not "allowed" for 1.20.4.
Manually adding it like @Blastshotting said is working.

So, getting the ressource pack updated to support the version 1.20.4 should be enough of a fix here.

So, same as here : https://github.com/PepperCode1/Continuity/issues/355

**Comment by YukiAyase** [comment] 2024-01-17 18:43
> I can confirm that, the ressource pack is not "allowed" for 1.20.4. Manually adding it like @Blastshotting said is working.
> 
> So, getting the ressource pack updated to support the version 1.20.4 should be enough of a fix here.
> 
> So, same as here : #355

# Please avoid necroing old thread and create your own thread providing your full log file

**Comment by Athar42** [comment] 2024-01-17 19:33
If "5 days ago" is "necroing" for you... ok...

But, I did edit my comment to add the other post (older), categorized as bug for the exact same issue, and you tell me to open a third thread at least for the exact same report ?
Sorry, but that's stupid.

And oh yes, logs are useless in that case.
Ressources pack integrated into Continuity just need to get a "bump in version" as the ressource pack version for 1.20.2 was 18, 1.20.3 + 1.20.4 is now 22 (as we can see in this release note page of Minecraft... https://www.minecraft.net/en-us/article/minecraft-java-edition-1-20-3 )

(And I reply just because I don't like the way you respond to me, in bold and bigger characters than needed... if you are not happy that I give my 2 cents, you can just write it normally, like this, else it's like a verbal aggression)

The only thing needed, to show that the RP is not supported by MC 1.20.4, but was made for an earlier version.
![image](https://github.com/PepperCode1/Continuity/assets/44590042/83175bf4-75ed-4644-aa91-702ed5b33e8b)


Now, do whatever you want, block me from this repo from posting anything, I was just here to help, without thinking I was doing something wrong... cya

**Comment by YukiAyase** [comment] 2024-01-17 19:43
> If "5 days ago" is "necroing" for you... ok...
> 
> But, I did edit my comment to add the other post (older), categorized as bug for the exact same issue, and you tell me to open a third thread at least for the exact same report ? Sorry, but that's stupid.

This thread was from 2 weeks ago with no activity from the op whatsoever
Having people create new threads makes it easier to talk with the op instead of flooding someone else's thread that can potentially jump from one person to another and GitHub has a default of emailing the op about their threads being active, yes creating new threads with the same problem will create duplicates but it makes conversations easier for op and whoever is helping them

> 
> And oh yes, logs are useless in that case. Ressources pack integrated into Continuity just need to get a "bump in version" as the ressource pack version for 1.20.2 was 18, 1.20.3 + 1.20.4 is now 22 (as we can see in this release note page of Minecraft... https://www.minecraft.net/en-us/article/minecraft-java-edition-1-20-3 )

Hopefully you do know that resource packs marked as "for older version" or "for newer version" will still work regardless as long as the resource pack is not from legacy Minecraft versions
And saying logs are useless in this situation, saying "same" or the likes doesn't help either, log files provides stack traces, errors and mods list which allows us to actually track the issue

**Comment by creamcitykitty** [comment] 2024-01-26 03:26
Get indium with Continuity and it should fix it not working

**Comment by PepperCode1** [comment] 2024-03-29 20:55
Please treat each other respectfully. This is really just a duplicate of #355.

**Closed as completed by PepperCode1** 2024-03-29 20:55 UTC
Labels: more information needed

**Comment by xXEclipseX** [comment] 2024-06-19 12:21
Continuity used to connect grass and dirt path textures and now it doesn't do it for no reason (i have induim downloaded)
does any one know any solutions (this problem accrued to me on these 2 versions [1.20.4/1.21] as i said it used to work and it just doesn't)

**Comment by YukiAyase** [comment] 2024-06-19 22:54
> Continuity used to connect grass and dirt path textures and now it doesn't do it for no reason (i have induim downloaded) does any one know any solutions (this problem accrued to me on these 2 versions [1.20.4/1.21] as i said it used to work and it just doesn't)

### Please avoid necroing old threads and create your own thread providing your log file and a screenshot of the issue (if possible), thank you.

**Comment by CorvidArekusu** [comment] 2024-08-01 02:41
Sorry for necroing an old thread instead of creating my own thread providing my log file and a screenshot of the issue (if possible).
