### ISSUE TITLE
Unable to launch in 1.19.3

### ISSUE THREAD

**Issue by Midnight-Bladez** [PepperCode1/Continuity#192] opened 2022-12-11 00:49 UTC
![Continuity](https://user-images.githubusercontent.com/120287117/206881257-2bc4bcbd-9f73-4604-a0ee-43520ef974a8.PNG)

**Comment by PepperCode1** [comment] 2022-12-11 00:52
Duplicate of #189.

**Closed as completed by PepperCode1** 2022-12-11 00:52 UTC

**Comment by Midnight-Bladez** [comment] 2022-12-11 00:55
No, i literally cant launch the game in 1.19.3, everything else works, but the moment i slot in continuity i get this error message. there is definitely an issue here

**Comment by PepperCode1** [comment] 2022-12-11 00:56
The issue is that Continuity is not updated to 1.19.3.

**Comment by Midnight-Bladez** [comment] 2022-12-11 01:02
ok, is there an estimate or anything on when it would get updated to the new version? it's listed at 1.19+ so i would assume that it'd work.

**Comment by PepperCode1** [comment] 2022-12-11 01:09
There is no estimated time. Where exactly is it listed as 1.19+?

**Comment by Midnight-Bladez** [comment] 2022-12-11 01:11
CurseForge

**Comment by PepperCode1** [comment] 2022-12-11 01:18
I do not see 1.19.3 listed here (supported versions of Continuity 2.0.1+1.19) or there being any mention of "1.19+". The "1.19" at the end of the version does not mean "1.19+", if that is what misled you.
![versions](https://user-images.githubusercontent.com/44146161/206881877-2aa22147-098e-4327-9933-2762c127b72c.jpg)

**Comment by Midnight-Bladez** [comment] 2022-12-11 01:22
Ah yeah, sorry about that, thanks for being quick with your replies. hope you have a good night/morning/evening.
