### ISSUE TITLE
[Bug] resourcepack loading

### ISSUE THREAD

**Issue by L9Tigrotto** [PepperCode1/Continuity#480] opened 2024-07-28 13:04 UTC
### Error

Rendering glass blocks
![image](https://github.com/user-attachments/assets/494b97f9-5d86-478d-8948-2187f9aa91e5)

The error is fixed reloading the resource packs.

### Mod installed:
- CaffeineConfig(caffeineconfig)@1.3.0+1.17
- cloth-basic-math(cloth-basic-math)@0.6.1
- Cloth Config v15(cloth-config)@15.0.128
- Common Protection API(common-protection-api)@1.0.0
- Continuity(continuity)@3.0.0-beta.5+1.21
- CraftTweaker(crafttweaker)@20.0.19
- Cull Leaves(cullleaves)@3.4.0
- Entity Model Features(entity_model_features)@2.1.3
- Entity Sound Features(entity_sound_features)@0.4
- Entity Texture Features(entity_texture_features)@6.1.3
- Fabric API(fabric-api)@0.100.7+1.21
- Fabric API Base(fabric-api-base)@0.4.42+6573ed8cd1
- Fabric API Lookup API (v1)(fabric-api-lookup-api-v1)@1.6.67+b5597344d1
- Fabric Biome API (v1)(fabric-biome-api-v1)@13.0.29+5bd9f1bcd1
- Fabric Block API (v1)(fabric-block-api-v1)@1.0.22+0af3f5a7d1
- Fabric BlockView API (v2)(fabric-block-view-api-v2)@1.0.10+6573ed8cd1
- Fabric BlockRenderLayer Registration (v1)(fabric-blockrenderlayer-v1)@1.1.52+0af3f5a7d1
- Fabric Client Tags(fabric-client-tags-api-v1)@1.1.15+6573ed8cd1
- Fabric Command API (v1)(fabric-command-api-v1)@1.2.49+f71b366fd1
- Fabric Command API (v2)(fabric-command-api-v2)@2.2.28+6ced4dd9d1
- Fabric Commands (v0)(fabric-commands-v0)@0.2.66+df3654b3d1
- Fabric Content Registries (v0)(fabric-content-registries-v0)@8.0.15+b5597344d1
- Fabric Convention Tags(fabric-convention-tags-v1)@2.0.18+7f945d5bd1
- Fabric Convention Tags (v2)(fabric-convention-tags-v2)@2.4.2+c111832ad1
- Fabric Crash Report Info (v1)(fabric-crash-report-info-v1)@0.2.29+0af3f5a7d1
- Fabric Data Attachment API (v1)(fabric-data-attachment-api-v1)@1.1.25+6a6dfa19d1
- Fabric Data Generation API (v1)(fabric-data-generation-api-v1)@20.2.12+16c4ae25d1
- Fabric Dimensions API (v1)(fabric-dimensions-v1)@4.0.0+6fc22b99d1
- Fabric Entity Events (v1)(fabric-entity-events-v1)@1.6.12+6fc22b99d1
- Fabric Events Interaction (v0)(fabric-events-interaction-v0)@0.7.10+e633f883d1
- Fabric Game Rule API (v1)(fabric-game-rule-api-v1)@1.0.53+6ced4dd9d1
- Fabric Item API (v1)(fabric-item-api-v1)@11.0.0+afdfc921d1
- Fabric Item Group API (v1)(fabric-item-group-api-v1)@4.1.3+78017270d1
- Fabric Key Binding API (v1)(fabric-key-binding-api-v1)@1.0.47+0af3f5a7d1
- Fabric Key Bindings (v0)(fabric-keybindings-v0)@0.2.45+df3654b3d1
- Fabric Lifecycle Events (v1)(fabric-lifecycle-events-v1)@2.3.11+8f3583aed1
- Fabric Loot API (v2)(fabric-loot-api-v2)@3.0.13+3f89f5a5d1
- Fabric Loot API (v3)(fabric-loot-api-v3)@1.0.1+3f89f5a5d1
- Fabric Message API (v1)(fabric-message-api-v1)@6.0.13+6573ed8cd1
- Fabric Model Loading API (v1)(fabric-model-loading-api-v1)@2.0.0+fe474d6bd1
- Fabric Networking API (v1)(fabric-networking-api-v1)@4.2.0+ab7edbacd1
- Fabric Object Builder API (v1)(fabric-object-builder-api-v1)@15.1.13+d1321076d1
- Fabric Particles (v1)(fabric-particles-v1)@4.0.2+6573ed8cd1
- fabric-permissions-api(fabric-permissions-api-v0)@0.2-SNAPSHOT
- Fabric Recipe API (v1)(fabric-recipe-api-v1)@5.0.10+65089712d1
- Fabric Registry Sync (v0)(fabric-registry-sync-v0)@5.0.25+5bd9f1bcd1
- Fabric Renderer API (v1)(fabric-renderer-api-v1)@3.3.0+0ae0b97dd1
- Fabric Renderer - Indigo(fabric-renderer-indigo)@1.6.5+48fb1586d1
- Fabric Renderer Registries (v1)(fabric-renderer-registries-v1)@3.2.68+df3654b3d1
- Fabric Rendering Data Attachment (v1)(fabric-rendering-data-attachment-v1)@0.3.48+73761d2ed1
- Fabric Rendering Fluids (v1)(fabric-rendering-fluids-v1)@3.1.6+b5597344d1
- Fabric Rendering (v0)(fabric-rendering-v0)@1.1.71+df3654b3d1
- Fabric Rendering (v1)(fabric-rendering-v1)@5.0.5+df16efd0d1
- Fabric Resource Conditions API (v1)(fabric-resource-conditions-api-v1)@4.2.1+d153f344d1
- Fabric Resource Loader (v0)(fabric-resource-loader-v0)@1.2.0+7e687b32d1
- Fabric Screen API (v1)(fabric-screen-api-v1)@2.0.24+b5597344d1
- Fabric Screen Handler API (v1)(fabric-screen-handler-api-v1)@1.3.82+b5597344d1
- Fabric Sound API (v1)(fabric-sound-api-v1)@1.0.23+6573ed8cd1
- Fabric Transfer API (v1)(fabric-transfer-api-v1)@5.1.15+3dccd343d1
- Fabric Transitive Access Wideners (v1)(fabric-transitive-access-wideners-v1)@6.0.12+6573ed8cd1
- Fabric Loader(fabricloader)@0.16.0
- Indium(indium)@1.0.34+mc1.21
- OpenJDK 64-Bit Server VM(java)@21
- Kirin UI(kirin)@1.19.0+1.21
- Language Reload(languagereload)@1.6.1+1.21
- MidnightLib(midnightlib)@1.5.7
- Minecraft(minecraft)@1.21
- MixinExtras(mixinextras)@0.4.0
- httpmime(org_apache_httpcomponents_httpmime)@4.5.10
- javassist(org_javassist_javassist)@3.29.0-GA
- reflections(org_reflections_reflections)@0.10.2
- Packet Tweaker(packet_tweaker)@0.5.5+1.21
- Placeholder API(placeholder-api)@2.4.1+1.21
- Polymer (Common)(polymer-common)@0.9.7+1.21
- Polymer (Core)(polymer-core)@0.9.7+1.21
- Polymer (Networking)(polymer-networking)@0.9.7+1.21
- Polymer (Registry Sync Manipulator)(polymer-registry-sync-manipulator)@0.9.7+1.21
- Polymer (Resource Pack)(polymer-resource-pack)@0.9.7+1.21
- Polymer (Virtual Entity)(polymer-virtual-entity)@0.9.7+1.21
- Predicate API(predicate-api)@0.5.1+1.21
- Presence Footsteps(presencefootsteps)@1.10.0+1.21
- Reese's Sodium Options(reeses-sodium-options)@1.7.3+mc1.21
- Remove Reloading Screen(rrls)@5.0.5+mc1.21-fabric
- Server Translations API(server_translations_api)@2.3.1+1.21-pre2
- sgui(sgui)@1.6.0+1.21
- Sodium(sodium)@0.5.11+mc1.21
- Sodium Extra(sodium-extra)@0.5.7+mc1.21
- Universal Graves(universal-graves)@3.4.2+1.21

 [Here](https://drive.google.com/file/d/1ADRtKiK6DQCvgP8Ogv-j3X43jsvsEcAs/view?usp=sharing)'s the mods zip.

**Comment by PepperCode1** [comment] 2024-08-01 20:54
Duplicate of #446.

**Closed as not planned by PepperCode1** 2024-08-01 20:54 UTC
