### ISSUE TITLE
texture pack not applying 

### ISSUE THREAD

**Issue by EnderManz54** [PepperCode1/Continuity#283] opened 2023-07-18 19:16 UTC
when i have the continuity mod on and try using some of my resource pack i get the this error  
![image](https://github.com/PepperCode1/Continuity/assets/139290219/fb7b4a6f-af15-4cf2-a576-061175776752)

**Comment by YukiAyase** [comment] 2023-07-18 20:39
Install [Indium](https://modrinth.com/mod/indium)


Duplicate of https://github.com/PepperCode1/Continuity/issues/107

**Closed as completed** 2023-07-22 14:48 UTC
