### ISSUE TITLE
Missing Grass Texture with Conquest Resource Pack

### ISSUE THREAD

**Issue by aschec** [PepperCode1/Continuity#194] opened 2022-12-20 19:16 UTC
Using the Conquest Resource Pack everything works fine except the Grass Block. The Top part is weirdly bugged (probably due to custom 3D models?) which makes it translucent. 
![2022-12-20_20 13 57-min](https://user-images.githubusercontent.com/113135609/208748524-edd1af14-d4ee-4501-901a-0691c86e6050.png)

**Comment by PepperCode1** [comment] 2022-12-20 19:17
Duplicate of #160.

**Closed as completed by PepperCode1** 2022-12-20 19:17 UTC
