### ISSUE TITLE
Random crashing during gameplay

### ISSUE THREAD

**Issue by likeusb** [PepperCode1/Continuity#352] opened 2023-12-17 04:42 UTC
Full log: https://mclo.gs/et1efkA

Upon playing for some time, the game crashes. Generally about a few minutes.

The log explicitly mentions issues with Sodium and Continuity, so I will hope that it is Continuity.

Any idea why?

**Comment by YukiAyase** [comment] 2023-12-17 08:03
Install [Indium](https://modrinth.com/mod/indium)

Duplicate of https://github.com/PepperCode1/Continuity/issues/107

**Comment by supergnaw** [comment] 2023-12-17 23:10
Random crashes are related to blocks falling from movement, such as blocks falling from gravity or pistons moving. The current version of Indium available on Modrinth is out of date and throws "Incompatible mods found!" error:

```
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sodium' (sodium) 0.5.5 with version 0.5.5 that is compatible with:
		 - indium, any version
	 - Replace mod 'Indium' (indium) 1.0.27+mc1.20.1 with any version that is compatible with:
		 - sodium, version 0.5.5
More details:
	 - Mod 'Indium' (indium) 1.0.27+mc1.20.1 requires version 0.5.3 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.5!
```

**Closed as completed** 2023-12-17 23:22 UTC
