### ISSUE TITLE
1.16.5?

### ISSUE THREAD

**Issue by WeebKun1000** [PepperCode1/Continuity#220] opened 2023-02-16 19:39 UTC
any 1.16.5 compatible alternative of version?

**Comment by Julienraptor01** [comment] 2023-02-20 14:36
no, you can use that instead https://github.com/TwilightFlower/connected-block-textures

**Comment by PepperCode1** [comment] 2023-02-20 18:16
Duplicate of #154. It may be ported back, but the chances are very low.

**Closed as completed by PepperCode1** 2023-02-20 18:16 UTC
