### ISSUE TITLE
1.19 Crash

### ISSUE THREAD

**Issue by kaxonomy** [PepperCode1/Continuity#147] opened 2022-07-29 02:27 UTC
This crash happens in the latest mod version usually when I'm spectating people on 1.19.
Crash Report:
[latest.log](https://github.com/PepperCode1/Continuity/files/9215557/latest.log)

**Comment by PepperCode1** [comment] 2022-07-29 02:36
Duplicate of #107. Install Indium.

**Closed as not planned by PepperCode1** 2022-07-29 02:36 UTC
