### ISSUE TITLE
Continuity not working in 1.18.2

### ISSUE THREAD

**Issue by KB-Q** [PepperCode1/Continuity#79] opened 2022-03-29 13:54 UTC
Doesn't work in 1.18.2, with sodium and indium. Glass and panes are not connecting. 

The texture packs continuity/default and continuity/glass_pane_culling are also weirdly getting deselected, have to select it manually everytime after loading a world. Even then, the glass and panes don't connect.

![image](https://user-images.githubusercontent.com/59303688/160627362-9baea14b-3e76-465a-bd72-34d946fa0e8c.png)

**Comment by PepperCode1** [comment] 2022-03-29 14:00
Closing until a log is provided.

**Comment by KB-Q** [comment] 2022-03-30 05:55
Where do I find the logs of a world?

**Comment by KB-Q** [comment] 2022-03-30 06:13
[2022-03-29-2.log.gz](https://github.com/PepperCode1/Continuity/files/8377453/2022-03-29-2.log.gz)
[2022-03-29-1.log.gz](https://github.com/PepperCode1/Continuity/files/8377455/2022-03-29-1.log.gz)
[latest.log](https://github.com/PepperCode1/Continuity/files/8377456/latest.log)

I hope these are enough, these are from the world I played within the last 12 hours...

**Comment by KB-Q** [comment] 2022-03-30 07:25
Let me know if there are any updates...

**Comment by KB-Q** [comment] 2022-03-30 16:28
> The texture packs continuity/default and continuity/glass_pane_culling are also weirdly getting deselected, have to select it manually everytime after loading a world.

Update: This is not actually a problem btw, it was just caused because I played some modpacks which deselected those two packs. 

However the main issue is still there, glass and panes don't connect with both packs enabled and both sodium and lithium installed.

Attaching my mod list from issue #80 for reference:
https://github.com/PepperCode1/Continuity/files/8381869/MC.modlist.Mar.2022.txt

**Comment by ghost** [comment] 2022-03-30 23:11
Experiencing same issue here.

**Comment by notLily72** [comment] 2022-03-30 23:16
I believe the issue is okzoomer’s bundling of QSL. If you want to use continuity you have to remove okzoomer.

**Comment by PepperCode1** [comment] 2022-03-31 04:46
@notLily72 is correct. Read the last comment in the duplicated issue for more information.
Duplicate of #68.

**Closed as completed by PepperCode1** 2022-03-31 04:46 UTC
