### ISSUE TITLE
Entity Falling Block

### ISSUE THREAD

**Issue by Qubixey** [PepperCode1/Continuity#272] opened 2023-07-04 11:35 UTC
when this mod is installed in your game,
if a sand block falls into water, the game will crash.

**Comment by YukiAyase** [comment] 2023-07-04 11:36
Install Indium
https://modrinth.com/mod/indium

**Comment by PepperCode1** [comment] 2023-07-08 15:20
Duplicate of #107.

**Closed as completed by PepperCode1** 2023-07-08 15:20 UTC
