### ISSUE TITLE
Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null

### ISSUE THREAD

**Issue by nijahplays** [PepperCode1/Continuity#126] opened 2022-06-17 21:22 UTC
[latest.log](https://github.com/PepperCode1/Continuity/files/8931358/latest.log)

Crashing with complementary re-imagined shaders / iris

**Comment by PepperCode1** [comment] 2022-06-17 21:24
Duplicate of #107.

**Closed as not planned by PepperCode1** 2022-06-17 21:24 UTC
