### ISSUE TITLE
1.19 the block Textures don't show in continuity

### ISSUE THREAD

**Issue by Robertpuggle** [PepperCode1/Continuity#108] opened 2022-06-08 11:38 UTC
![2022-06-08_06 35 43](https://user-images.githubusercontent.com/40573140/172607235-4d7515f5-e43f-4ed9-bbf2-e9616292bb30.png)

**These is Wat I mean**

**Comment by PepperCode1** [comment] 2022-06-09 05:43
Duplicate of #107.

**Closed as completed by PepperCode1** 2022-06-09 05:43 UTC
