### ISSUE TITLE
Custom block layers apply to solid blocks and legacy packs use weight property incorrectly

### ISSUE THREAD

**Issue by Sweenus** [PepperCode1/Continuity#160] opened 2022-08-20 11:10 UTC
Using the conquest_ resource pack on both 1.18.2 and 1.19 with continuity isn't connecting all intended textures, and is causing transparency issues with grass blocks (less so with shaders enabled). Is the conquest_ using optifine features that just aren't supported by continuity, and if so, will they be supported in future? Examples below (All examples have the two optional continuity packs enabled):

Image 1
Resource pack: Conquest_
Mods: Continuity
![enter image description here](https://imgur.com/LJkASvo.jpg)
-Partial connected texture issues
-Transparent grass blocks

Image 2
Resource Pack: Conquest_
Mods: Continuity, Sodium, Indium
![enter image description here](https://imgur.com/CqArVzG.jpg)
-Partial connected texture issues
-Severe Transparent grass blocks

Image 3
Resource Pack: Conquest_
+ Shaders enabled via Iris
Mods: Continuity, Sodium, Indium, Iris
![enter image description here](https://i.imgur.com/jRVwkVK.jpg)
-Partial connected texture issues
-Slight transparent grass blocks (hard to see in the image, but the edges of some grass textures are still transparent)

Image 4
Resource Pack: Conquest_
Mods: Optifine, Optifabric
![enter image description here](https://i.imgur.com/fE7WOoe.jpg)
This is how it should look - grass & sand connection working. No transparency.

Image 5
Resource pack: John Smith
Mods: Continuity
![enter image description here](https://i.imgur.com/X9BS9PN.jpg)
This resource pack connects fine - probably not using advanced optifine features

Image 6
Resource pack: Yuushya
Mods: Continuity
![enter image description here](https://i.imgur.com/awAMFEp.png)
This resource pack connects fine - probably not using advanced optifine features

The sand/grass is just one example. The texture connections are off for a variety of blocks.

**Comment by PepperCode1** [comment] 2022-08-20 16:02
This is not related to "advanced Optifine features". Continuity supports all CTM features. The transparency bug is caused by Continuity not checking for a full cube when when applying custom block layers from `block.properties`. You will see that disabling the custom block layers option in the Continuity configuration fixes the issue. This will be fixed for 2.0.2.
The sand overlay problem is separate and is caused by some very minor parity difference in the CTM code that I may or may not be able to find and fix.

**Comment by PepperCode1** [comment] 2022-10-16 16:19
I found the cause of the overlay issue some time ago so I will put it here as well. Continuity supports the `weight` property from MCPatcher while Optifine does not, but because the pack is so old and was never rewritten, it still has `weight`s in some files that do nothing on Optifine but cause issues on Continuity because no one has actually tested the pack with those weights re-enabled. Clearly this property will need to be disabled by default to fix this, but I have not yet decided how to allow packs to re-enable it.

**Comment by PepperCode1** [comment] 2022-10-18 18:12
The first part of this issue has been fixed in 19821bcebb50c2b69f5e01460f0f8ec1a5500b43.

**Comment by aschec** [comment] 2022-12-20 19:34
Where can i find the configuration for continuity?

**Comment by PepperCode1** [comment] 2022-12-20 19:40
Install ModMenu, open the mod menu in-game, select Continuity, and press the gear icon.

**Closed as completed** 2023-02-05 20:00 UTC
Labels: bug
