### ISSUE TITLE
Incompatibility with Inspecio

### ISSUE THREAD

**Issue by SyberiaK** [PepperCode1/Continuity#92] opened 2022-05-08 16:14 UTC
When i have Continuity + Inspecio installed, there are no connected textures.

**Comment by PepperCode1** [comment] 2022-05-08 16:27
Duplicate of #68. Inspecio's developer said that an update for Fabric that will fix the issue will not be released, so you will have to either uninstall Inspecio or switch to Quilt and update to Inspecio 1.4.0.

**Closed as completed by PepperCode1** 2022-05-08 16:27 UTC

**Comment by SyberiaK** [comment] 2022-05-08 16:32
Thanks, i found that it updates without switching, so i'm very happy now :)
