### ISSUE TITLE
Water flowing over ice causes weird visuals

### ISSUE THREAD

**Issue by ElephantUp** [PepperCode1/Continuity#262] opened 2023-06-14 20:17 UTC
These are the mods I currently have installed:
![image](https://github.com/PepperCode1/Continuity/assets/136644986/aa6dadae-6e70-498a-9e82-dd8cdccd5ca1)
I am playing on Fabric 1.20.1
This is what happens when water flows over ice:

https://github.com/PepperCode1/Continuity/assets/136644986/97c6888b-7fc7-4f66-be12-2cf9c5216019

I know this is a bug with Continuity, since if I take is out of my mods folder, the game looks normal.

**Comment by PepperCode1** [comment] 2023-06-14 20:22
Duplicate of CaffeineMC/sodium-fabric#38. This is not a Continuity issue.

**Closed as completed by PepperCode1** 2023-06-14 20:22 UTC
