### ISSUE TITLE
Exception occurred while loading resource pack

### ISSUE THREAD

**Issue by 4o4E** [PepperCode1/Continuity#200] opened 2023-01-03 14:12 UTC
[resource pack](https://github.com/4o4E/DynamicGlowOre/releases/download/2022.06.22/DynamicGlowOre_1.17+.zip)

```log
[19:04:01] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.12
[19:04:01] [main/INFO]: Loading 59 mods:
	- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
	- continuity 2.0.1+1.19
	- dynamicfps 2.2.0
	- fabric-api 0.71.0+1.19.2
	- fabric-api-base 0.4.14+6e0787e690 via fabric-api
	- fabric-api-lookup-api-v1 1.6.13+93d8cb8290 via fabric-api
	- fabric-biome-api-v1 9.1.0+82db024a90 via fabric-api
	- fabric-block-api-v1 1.0.2+e415d50e90 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.23+c6af733c90 via fabric-api
	- fabric-client-tags-api-v1 1.0.4+b35fea8390 via fabric-api
	- fabric-command-api-v1 1.2.14+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.1.10+93d8cb8290 via fabric-api
	- fabric-commands-v0 0.2.31+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.40+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.5.0+7c6cd14d90 via fabric-api
	- fabric-convention-tags-v1 1.2.1+27265b3490 via fabric-api
	- fabric-crash-report-info-v1 0.2.8+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.3.5+2d2baf4b90 via fabric-api
	- fabric-dimensions-v1 2.1.34+0d0f210290 via fabric-api
	- fabric-entity-events-v1 1.5.3+9244241690 via fabric-api
	- fabric-events-interaction-v0 0.4.33+562bff6e90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.33+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.24+b6b6abb490 via fabric-api
	- fabric-item-api-v1 1.6.3+9785ec3590 via fabric-api
	- fabric-item-groups-v0 0.3.37+9244241690 via fabric-api
	- fabric-key-binding-api-v1 1.0.25+5c4fce2890 via fabric-api
	- fabric-keybindings-v0 0.2.23+df3654b390 via fabric-api
	- fabric-lifecycle-events-v1 2.2.3+1b46dc7890 via fabric-api
	- fabric-loot-api-v2 1.1.11+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.14+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.6+93d8cb8290 via fabric-api
	- fabric-mining-level-api-v1 2.1.22+33fbc73890 via fabric-api
	- fabric-models-v0 0.3.20+c6af733c90 via fabric-api
	- fabric-networking-api-v1 1.2.10+10eb22f490 via fabric-api
	- fabric-networking-v0 0.3.27+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.1.5+9785ec3590 via fabric-api
	- fabric-particles-v1 1.0.13+4d0d570390 via fabric-api
	- fabric-registry-sync-v0 0.9.31+9244241690 via fabric-api
	- fabric-renderer-api-v1 1.2.0+2e5408b590 via fabric-api
	- fabric-renderer-indigo 0.7.0+2e5408b590 via fabric-api
	- fabric-renderer-registries-v1 3.2.23+df3654b390 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.18+6e0787e690 via fabric-api
	- fabric-rendering-fluids-v1 3.0.10+4d0d570390 via fabric-api
	- fabric-rendering-v0 1.1.26+df3654b390 via fabric-api
	- fabric-rendering-v1 1.12.0+08b73de490 via fabric-api
	- fabric-resource-conditions-api-v1 2.1.2+aae9039d90 via fabric-api
	- fabric-resource-loader-v0 0.8.3+251d254a90 via fabric-api
	- fabric-screen-api-v1 1.0.31+4d0d570390 via fabric-api
	- fabric-screen-handler-api-v1 1.3.6+1cc24b1b90 via fabric-api
	- fabric-sound-api-v1 1.0.2+c4f28df590 via fabric-api
	- fabric-textures-v0 1.0.23+aeb40ebe90 via fabric-api
	- fabric-transfer-api-v1 2.1.4+4d0d570390 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.3+08b73de490 via fabric-api
	- fabricloader 0.14.12
	- java 17
	- minecraft 1.19.2
	- modmenu 4.1.2
	- org_joml_joml 1.10.4 via sodium
	- sodium 0.4.4+build.18
[19:04:01] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/F:/D/fabric%201.19.2/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[19:04:02] [main/INFO]: Compatibility level set to JAVA_17
[19:04:02] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 0 override(s) found
[19:04:04] [main/INFO]: Building optimized datafixer
[19:04:07] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:04:08] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:155) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:161) ~[authlib-3.11.49.jar:?]
	at net.minecraft.class_310.method_31382(class_310.java:711) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:431) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:205) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.12.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:87) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-3.11.49.jar:?]
	... 9 more
[19:04:08] [Render thread/INFO]: Setting user: 404E
[19:04:09] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[19:04:10] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[19:04:10] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[19:04:11] [Worker-Main-12/ERROR]: Failed to retrieve profile key pair
java.io.IOException: Could not retrieve profile key pair
	at net.minecraft.class_7434.method_43605(class_7434.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_7434.method_44291(class_7434.java:69) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[19:04:11] [Render thread/INFO]: Narrator library for x64 successfully loaded
[19:04:11] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Continuity, Dynamic FPS, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric Block API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Client Tags, Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Sound API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Mod Menu, Sodium)
[19:04:13] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[19:04:14] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[19:04:14] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[19:04:14] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on 扬声器 (High Definition Audio Device)
[19:04:14] [Render thread/INFO]: Sound engine started
[19:04:15] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[19:04:15] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[19:04:15] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[19:04:15] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[19:04:15] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[19:04:15] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[19:04:15] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[19:04:15] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[19:04:15] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[19:04:15] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[19:04:15] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[19:04:26] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Continuity, Dynamic FPS, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric Block API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Client Tags, Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Sound API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Mod Menu, Sodium), DynamicGlowOre_1.17+.zip
[19:04:26] [Worker-Bootstrap-3/INFO]: 4283 Datafixer optimizations took 21808 milliseconds
[19:04:27] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[19:04:27] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[19:04:27] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on 扬声器 (High Definition Audio Device)
[19:04:27] [Render thread/INFO]: Sound engine started
[19:04:27] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[19:04:27] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[19:04:27] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[19:04:27] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[19:04:27] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[19:04:27] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[19:04:27] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[19:04:27] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.ExceptionInInitializerError
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:68) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:68) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:68) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:68) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:68) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:68) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:211) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:198) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:315) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1205) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.12.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at me.pepperbell.continuity.client.model.EmissiveUnbakedModel.wrapBaked(EmissiveUnbakedModel.java:26) ~[continuity-2.0.1+1.19.jar:?]
	at me.pepperbell.continuity.client.model.WrappingUnbakedModel.method_4753(WrappingUnbakedModel.java:52) ~[continuity-2.0.1+1.19.jar:?]
	at net.minecraft.class_1088.method_15878(class_1088.java:481) ~[client-intermediary.jar:?]
	at net.minecraft.class_807.method_4753(class_807.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088.method_15878(class_1088.java:481) ~[client-intermediary.jar:?]
	at me.pepperbell.continuity.client.model.WrappingUnbakedModel.method_4753(WrappingUnbakedModel.java:49) ~[continuity-2.0.1+1.19.jar:?]
	at net.minecraft.class_1088.method_15878(class_1088.java:481) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088.method_4733(class_1088.java:250) ~[client-intermediary.jar:?]
	at java.util.HashMap$KeySet.forEach(HashMap.java:1008) ~[?:?]
	at net.minecraft.class_1088.method_18177(class_1088.java:247) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_18179(class_1092.java:67) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_18788(class_1092.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 65 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.materialFinder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at me.pepperbell.continuity.client.util.RenderUtil.lambda$static$0(RenderUtil.java:38) ~[continuity-2.0.1+1.19.jar:?]
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305) ~[?:?]
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195) ~[?:?]
	at java.lang.ThreadLocal.get(ThreadLocal.java:172) ~[?:?]
	at me.pepperbell.continuity.client.util.RenderUtil.getMaterialFinder(RenderUtil.java:93) ~[continuity-2.0.1+1.19.jar:?]
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.<clinit>(EmissiveBakedModel.java:35) ~[continuity-2.0.1+1.19.jar:?]
	at me.pepperbell.continuity.client.model.EmissiveUnbakedModel.wrapBaked(EmissiveUnbakedModel.java:26) ~[continuity-2.0.1+1.19.jar:?]
	at me.pepperbell.continuity.client.model.WrappingUnbakedModel.method_4753(WrappingUnbakedModel.java:52) ~[continuity-2.0.1+1.19.jar:?]
	at net.minecraft.class_1088.method_15878(class_1088.java:481) ~[client-intermediary.jar:?]
	at net.minecraft.class_807.method_4753(class_807.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088.method_15878(class_1088.java:481) ~[client-intermediary.jar:?]
	at me.pepperbell.continuity.client.model.WrappingUnbakedModel.method_4753(WrappingUnbakedModel.java:49) ~[continuity-2.0.1+1.19.jar:?]
	at net.minecraft.class_1088.method_15878(class_1088.java:481) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088.method_4733(class_1088.java:250) ~[client-intermediary.jar:?]
	at java.util.HashMap$KeySet.forEach(HashMap.java:1008) ~[?:?]
	at net.minecraft.class_1088.method_18177(class_1088.java:247) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_18179(class_1092.java:67) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_18788(class_1092.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 65 more
[19:04:27] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Continuity, Dynamic FPS, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric Block API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Client Tags, Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Sound API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Mod Menu, Sodium)
[19:04:27] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[19:04:27] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[19:04:27] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on 扬声器 (High Definition Audio Device)
[19:04:27] [Render thread/INFO]: Sound engine started
[19:04:27] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[19:04:27] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[19:04:27] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[19:04:27] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[19:04:27] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[19:04:27] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[19:04:27] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[19:04:28] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[19:04:28] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[19:04:28] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[19:04:28] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
```

**Comment by PepperCode1** [comment] 2023-01-03 18:15
Duplicate of #107; Install Indium.

**Closed as completed by PepperCode1** 2023-01-03 18:15 UTC
