### ISSUE TITLE
emissive textures Z-Fighting

### ISSUE THREAD

**Issue by GrenFlem** [PepperCode1/Continuity#346] opened 2023-12-07 05:06 UTC
title explains it. install continuity, get an emissive ore texture (_e) and watch it z-fight
![image_2023-12-06_210540793](https://github.com/PepperCode1/Continuity/assets/108261952/3c8d4474-ae89-484a-a0cb-160de810ee70)

**Comment by GrenFlem** [comment] 2023-12-07 05:07
![image_2023-12-06_210744845](https://github.com/PepperCode1/Continuity/assets/108261952/b55bd0d6-50bb-49fb-9208-56ce0efc6973)

**Comment by PepperCode1** [comment] 2023-12-07 06:08
Duplicate of #292.

**Closed as completed by PepperCode1** 2023-12-07 06:08 UTC
