### ISSUE TITLE
crash with falling block entities

### ISSUE THREAD

**Issue by micrwvae** [PepperCode1/Continuity#135] opened 2022-06-28 19:01 UTC
[crash-2022-06-28_20.12.09-client.txt](https://github.com/PepperCode1/Continuity/files/9003952/crash-2022-06-28_20.12.09-client.txt)

my game crashed twice when there were falling block entities on screen
it happend twice with different blocks

after seeing the mod beeing mentioned in the crash log i removed it and it didnt crash

**Comment by PepperCode1** [comment] 2022-06-28 19:23
Duplicate of #107.

**Closed as not planned by PepperCode1** 2022-06-28 19:23 UTC
