### ISSUE TITLE
Could you please add the NeoForge tag to your mod?

### ISSUE THREAD

**Issue by DarthCaesium** [PepperCode1/Continuity#536] opened 2024-10-30 17:13 UTC
I'm trying to make a NeoForge modpack on CurseForge that includes your mod, but CurseForge requires any Fabric mod to be tagged for NeoForge in order to use it with Sinytra Connector and publish the modpack.

**Comment by clo4** [comment] 2024-11-02 02:58
This mod doesn't run on NeoForge. Marking this mod as being supported on a modloader that it does not support would be both incorrect and extremely misleading. That's CurseForge's problem that they don't let you do that, not an individual modder's problem to deal with.

**Comment by VaporeonScripts** [comment] 2024-11-11 06:20
could add a neoforge tag and put connector and forgified fabric api as needed, that worked with clean f3 mod

**Comment by v3xed-v0id** [comment] 2024-11-24 19:25
> This mod doesn't run on NeoForge. Marking this mod as being supported on a modloader that it does not support would be both incorrect and extremely misleading. That's CurseForge's problem that they don't let you do that, not an individual modder's problem to deal with.

Not true, this mod is supposedly supported on neoforge via connector and forgified fabric api, marking support on official mod pages would not be incorrect, assuming that connector/forgified fabric api was declared as a hard dependency for this mod on neoforge.

Lets not spread misinformation, shall we?

**Comment by VaporeonScripts** [comment] 2024-11-24 19:42
Correct,the mod runs fine and well on neoforge ,just like clean f3 did,they marked as neo compatible while putting ffapi and connector as needed dependencies

**Comment by PepperCode1** [comment] 2024-11-26 18:59
Duplicate of #530.

**Closed as not planned by PepperCode1** 2024-11-26 18:59 UTC
