### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by piiko** [PepperCode1/Continuity#293] opened 2023-08-05 12:25 UTC
Minecraft stops loading with 95%~ done, but as soon as I disable the mod, it loads just fine.

What I found in the logs?
"Invalid path minecraft:optifine/ctm/metals_and_gems/copper/oxidized copper/1_e.png: Invalid segment 'oxidized copper' in path 'optifine/ctm/metals_and_gems/copper/oxidized copper/1_e.png'" 0-4
"Invalid path minecraft:optifine/ctm/bone block/top/0_e.png: Invalid segment 'bone block' in path 'optifine/ctm/bone block/top/0_e.png" 0-4
"Invalid path minecraft:optifine/ctm/bone block/side/0_e.png: Invalid segment 'bone block' in path 'optifine/ctm/bone block/side/0_e.png" 0-3
"Invalid path minecraft:optifine/ctm/basalt/polished side/0_e.png: Invalid segment 'polished side' in path 'optifine/ctm/basalt/polished side/0_e.png" 0-3

What caused it? idk, latest update of sodium I suppose

**Comment by YukiAyase** [comment] 2023-08-05 12:27
Please send the full log file instead
The one in .minecraft/logs with the filename "latest"

**Comment by piiko** [comment] 2023-08-06 00:14
[latest.log](https://github.com/PepperCode1/Continuity/files/12268468/latest.log)

**Comment by YukiAyase** [comment] 2023-08-06 00:22
Install Indium
https://modrinth.com/mod/indium/version/1.0.23+mc1.20.1

Duplicate of https://github.com/PepperCode1/Continuity/issues/107

**Closed as completed** 2023-08-06 04:33 UTC
