### ISSUE TITLE
[Bug] Built-in pack not loading properly

### ISSUE THREAD

**Issue by TAKfsg** [PepperCode1/Continuity#72] opened 2022-03-16 22:52 UTC
The built-in resource pack does not load properly and the connected textures do not appear. This could maybe be caused by the separate default and programmer-art folders inside the built-in resource pack because this only affects the built-in pack. Other packs, such as Compliance seem to work just fine.

Using MacOS on a MacBookPro 13" 2020 with M1 chip and 8GB of memory.

![image](https://user-images.githubusercontent.com/73729536/158704061-852e74bd-df75-479c-b6cd-b039915b8ace.png)
![image](https://user-images.githubusercontent.com/73729536/158704090-eb5d9ddb-882d-406a-9b8e-eebc9a1b3cba.png)

**Comment by notLily72** [comment] 2022-03-16 22:53
Can you provide a log file of the game

**Comment by PepperCode1** [comment] 2022-03-16 22:58
Duplicate of #68.

**Closed as completed by PepperCode1** 2022-03-16 22:58 UTC
