### ISSUE TITLE
resouce reload failed

### ISSUE THREAD

**Issue by BruhKidBruh** [PepperCode1/Continuity#368] opened 2024-02-05 11:56 UTC
When you try to use any connected textures pack it will give you this error

**Comment by YukiAyase** [comment] 2024-02-05 11:58
Please send your log file located in **.minecraft/logs**, the filename is **"latest"**

**Comment by BruhKidBruh** [comment] 2024-02-05 13:00
[latest.log](https://github.com/PepperCode1/Continuity/files/14165969/latest.log)

**Comment by BogDog72** [comment] 2024-02-05 14:13
This is happening to me as well. I will put my log in too. 
[latest.log](https://github.com/PepperCode1/Continuity/files/14166745/latest.log)

**Comment by YukiAyase** [comment] 2024-02-05 19:04
> [latest.log](https://github.com/PepperCode1/Continuity/files/14165969/latest.log)

Install [Indium](https://modrinth.com/mod/indium)

Duplicate of https://github.com/PepperCode1/Continuity/issues/107

P.S.
Indium has not officially updated yet to support latest versions of Sodium 0.5.6-0.5.8

**Comment by YukiAyase** [comment] 2024-02-05 19:13
> This is happening to me as well. I will put my log in too. [latest.log](https://github.com/PepperCode1/Continuity/files/14166745/latest.log)


### Update Sodium, Iris and Indium

**And again, Indium has not officially updated yet to support latest versions of Sodium
So use a slightly outdated version of Sodium which will be 0.5.3 and Iris will be 1.6.11 with the latest version of Indium which is currently 1.0.27 for Minecraft 1.20.1**

**Closed as completed** 2024-02-05 19:13 UTC

**Comment by YukiAyase** [comment] 2024-02-05 21:14
# Indium has [updated](https://modrinth.com/mod/indium/version/1.0.29+mc1.20.4) for Sodium 0.5.8
