### ISSUE TITLE
Game Crashes when blocks start falling

### ISSUE THREAD

**Issue by TomtomFH** [PepperCode1/Continuity#416] opened 2024-05-13 09:58 UTC
if a block starts falling like sand or black concrete powder the game instantly crashes

**Comment by YukiAyase** [comment] 2024-05-13 10:18
Install [Indium](https://modrinth.com/mod/indium/version/1.0.30+mc1.20.4)

Duplicate of https://github.com/PepperCode1/Continuity/issues/107

**Closed as completed** 2024-05-15 05:26 UTC
