### ISSUE TITLE
Game crashes when rendering moving_piston. (1.20.1 - continuity 3.0.0-beta.2+1.20 - Fabric API Fabric API 0.85.0+1.20.1)

### ISSUE THREAD

**Issue by Timicasto** [PepperCode1/Continuity#282] opened 2023-07-16 14:12 UTC
```Time: 2023-07-16 19:56:12
Description: Rendering Block Entity

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at me.pepperbell.continuity.impl.client.ProcessingContextImpl.<init>(ProcessingContextImpl.java:19)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.<init>(CTMBakedModel.java:83)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.<init>(ModelObjectsContainer.java:10)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:361)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:226)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:169)
	at me.pepperbell.continuity.client.model.ModelObjectsContainer.get(ModelObjectsContainer.java:18)
	at me.pepperbell.continuity.impl.client.ContinuityFeatureStatesImpl.get(ContinuityFeatureStatesImpl.java:16)
	at me.pepperbell.continuity.api.client.ContinuityFeatureStates.get(ContinuityFeatureStates.java:10)
	at net.minecraft.class_835.handler$zeb000$continuity$beforeRenderModels(class_835.java:518)
	at net.minecraft.class_835.method_3576(class_835.java:39)
	at net.minecraft.class_835.method_3569(class_835.java:20)
	at net.minecraft.class_824.method_23079(class_824.java:90)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:275)
	at net.minecraft.class_761.handler$bia000$sodium$onRenderTileEntities(class_761.java:10608)
	at net.minecraft.class_761.method_22710(class_761.java:1372)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)
```

Seems like some model failed to bake due to an API error? .. weird problem.
POC: activating a sticky piston.

Full crash-report below
[crash-2023-07-16_19.56.12-client.txt](https://github.com/PepperCode1/Continuity/files/12064243/crash-2023-07-16_19.56.12-client.txt)

**Comment by PepperCode1** [comment] 2023-07-16 14:43
Install Indium; Duplicate of #107.

**Closed as completed by PepperCode1** 2023-07-16 14:43 UTC
