### ISSUE TITLE
Texture continuity doesn't work

### ISSUE THREAD

**Issue by Hramchik** [PepperCode1/Continuity#361] opened 2024-01-12 17:11 UTC
Minecraft version 1.20.4
![image](https://github.com/PepperCode1/Continuity/assets/96018004/3d4d1b9e-6d2e-4619-a133-0617fc7284ed)
![image](https://github.com/PepperCode1/Continuity/assets/96018004/352855c0-7ca2-4088-8535-f4992bed217c)

**Comment by YukiAyase** [comment] 2024-01-12 17:15
Please upload your log file located in **.minecraft/logs, filename is "latest"**

**Comment by Hramchik** [comment] 2024-01-12 17:24
[latest.log](https://github.com/PepperCode1/Continuity/files/13922282/latest.log)

**Comment by YukiAyase** [comment] 2024-01-12 17:25
Install [Indium](https://modrinth.com/mod/indium)

Duplicate of https://github.com/PepperCode1/Continuity/issues/107

**Closed as completed** 2024-01-12 21:03 UTC
