### ISSUE TITLE
Textures Not Connecting

### ISSUE THREAD

**Issue by Cmcc1017** [PepperCode1/Continuity#327] opened 2023-10-31 03:47 UTC
Pretty self-explanitory

**Comment by Cmcc1017** [comment] 2023-10-31 03:52
![image](https://github.com/PepperCode1/Continuity/assets/149454637/f5f1c5a4-a31a-44ac-9b18-1b0058681f7f)

**Comment by Cmcc1017** [comment] 2023-10-31 03:53
![image](https://github.com/PepperCode1/Continuity/assets/149454637/77d303bb-8f90-4b9c-b690-64dde3992a9c)

**Comment by PepperCode1** [comment] 2023-11-03 16:37
Please provide your mod list.

**Comment by dpaulos6** [comment] 2023-11-05 13:31
Is there any known mod that could make continuity not work?

**Comment by ForestTrees** [comment] 2023-11-06 10:28
I meet the same problem.
I installed Sodium, but even though I installed the Indium mod, Continuity still doesn't work.

**Comment by YukiAyase** [comment] 2023-11-06 10:31
> I meet the same problem. I installed Sodium, but even though I installed the Indium mod, Continuity still doesn't work.

Have you enabled Continuity's resourcepacks?

If you have and its still not working
Please create your own support thread and attach your log file, it can be found in .minecraft/logs, filename is "latest"

**Comment by dpaulos6** [comment] 2023-11-06 10:58
> > I meet the same problem. I installed Sodium, but even though I installed the Indium mod, Continuity still doesn't work.
> 
> Have you enabled Continuity's resourcepacks?
> 
> If you have and its still not working Please create your own support thread and attach your log file, it can be found in .minecraft/logs, filename is "latest"

I did enable Continuity's resourcepacks and even installed additional ones, and still doesn't work.

**Comment by ForestTrees** [comment] 2023-11-06 11:32
> > I meet the same problem. I installed Sodium, but even though I installed the Indium mod, Continuity still doesn't work.
> 
> Have you enabled Continuity's resourcepacks?
> 
> If you have and its still not working Please create your own support thread and attach your log file, it can be found in .minecraft/logs, filename is "latest"

Thanks for your kindly remind. After checking, the previous error was caused by the resource package not being loaded correctly, and it returned to normal after reloading.

**Comment by PepperCode1** [comment] 2023-12-08 06:54
Closing due to lack of information.

**Closed as completed by PepperCode1** 2023-12-08 06:54 UTC
