### ISSUE TITLE
Crashing in 1.19.2

### ISSUE THREAD

**Issue by Doggy09** [PepperCode1/Continuity#186] opened 2022-11-14 01:57 UTC
I was playing with other mods in 1.19.2 and after a while of playing and them I stared having crashes and looked for help in the Fabric MC Discord and was told it was because this Mod was crashing
<img width="540" alt="image" src="https://user-images.githubusercontent.com/62355374/201559097-8fd1d130-55cd-4ed5-b91f-03ccc0da2fbd.png">
Here is the Crash log [https://crashy.net/63iFTv3diob5osbprBsf](url)

Details:
1.19.2
Other mods where present
No CTM was present
Started after a few hours of play time and crashes every once in a while, when in or joining single player world
Version 2.0.1
I have both Sodium and Indium
All my mods are up to date.

This may not be because of this mod but I was told in report this as an issue
<img width="306" alt="image" src="https://user-images.githubusercontent.com/62355374/201559242-1b9272c5-c0e5-4ff9-97f9-3043dca70a58.png">

**Comment by PepperCode1** [comment] 2022-11-14 01:58
You say you have Indium, but the log says otherwise. Duplicate of #107.

**Closed as completed by PepperCode1** 2022-11-14 01:58 UTC
